package linkcrypto

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"reflect"
	"testing"
)

// The shared golden vectors every client is pinned to. Generated by
// web/scripts/gen-crypto-vectors.mjs from libsodium itself and read — never
// copied — by the Web, Swift and Android suites; this is the Go reader.
//
// The path is relative to this package directory, so `go test` finds it from
// the module wherever the checkout lives. A missing or unreadable file is a
// FAILURE, never a skip: a vector suite that silently passes without its vectors
// is the gate that cannot fail.
const vectorsPath = "../../../apps/RelayiumKit/Tests/Fixtures/crypto-vectors.json"

type vectorKeyPair struct {
	Pub string `json:"pub"`
	Sec string `json:"sec"`
}

type cryptoVectors struct {
	Alice   vectorKeyPair `json:"alice"`
	Bob     vectorKeyPair `json:"bob"`
	Session struct {
		AliceSend string `json:"aliceSend"`
		AliceRecv string `json:"aliceRecv"`
		BobSend   string `json:"bobSend"`
		BobRecv   string `json:"bobRecv"`
	} `json:"session"`
	SAS    string `json:"sas"`
	Commit struct {
		Nonce string `json:"nonce"`
		Value string `json:"value"`
	} `json:"commit"`
	AEAD struct {
		KeyHex string `json:"keyHex"`
		Seq    uint64 `json:"seq"`
		PtHex  string `json:"ptHex"`
		CtHex  string `json:"ctHex"`
	} `json:"aead"`
	ResumeAuth struct {
		KeyHex  string `json:"keyHex"`
		Payload string `json:"payload"`
		MAC     string `json:"mac"`
	} `json:"resumeAuth"`
	TextKeys struct {
		Domain        string `json:"domain"`
		AliceTextSend string `json:"aliceTextSend"`
		AliceTextRecv string `json:"aliceTextRecv"`
		BobTextSend   string `json:"bobTextSend"`
		BobTextRecv   string `json:"bobTextRecv"`
	} `json:"textKeys"`
}

// loadVectors reads the fixture strictly: an unknown field fails, so a block
// added to the shared file cannot land with the Go reader silently ignoring it,
// an empty string field fails, so a renamed key cannot decode to "" and then be
// "matched" by nothing, and anything but whitespace after the one vector object
// fails, so the file must be a single complete JSON document.
func loadVectors(t *testing.T) cryptoVectors {
	t.Helper()
	raw, err := os.ReadFile(vectorsPath)
	if err != nil {
		t.Fatalf("shared crypto vectors are required, not optional: %v", err)
	}
	v, err := decodeVectors(raw)
	if err != nil {
		t.Fatalf("%s: %v", vectorsPath, err)
	}
	return v
}

func decodeVectors(raw []byte) (cryptoVectors, error) {
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	var v cryptoVectors
	if err := dec.Decode(&v); err != nil {
		return v, fmt.Errorf("decode strictly: %w", err)
	}
	// dec.More only reports whether another element follows inside an open
	// array or object; at top level it is false before a stray '}' or ']', so
	// "{...}}" would pass. Decoding once more must hit io.EOF: whitespace does,
	// a second value decodes, and a stray delimiter or junk is a syntax error.
	var extra json.RawMessage
	switch err := dec.Decode(&extra); {
	case err == nil:
		return v, fmt.Errorf("trailing data after the vector object: a second JSON value")
	case err != io.EOF:
		return v, fmt.Errorf("trailing data after the vector object: %w", err)
	}
	if err := requireNoEmptyStrings(reflect.ValueOf(v), "vectors"); err != nil {
		return v, err
	}
	return v, nil
}

func requireNoEmptyStrings(v reflect.Value, path string) error {
	switch v.Kind() {
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			if err := requireNoEmptyStrings(v.Field(i), path+"."+v.Type().Field(i).Name); err != nil {
				return err
			}
		}
	case reflect.String:
		if v.Len() == 0 {
			return fmt.Errorf("%s is missing or empty", path)
		}
	}
	return nil
}

// The reader itself is a gate, so it is tested against the real fixture bytes
// with in-memory edits; the shared file is never written.
func TestVectorsReaderRequiresOneCompleteDocument(t *testing.T) {
	raw, err := os.ReadFile(vectorsPath)
	if err != nil {
		t.Fatalf("shared crypto vectors are required, not optional: %v", err)
	}
	if _, err := decodeVectors(raw); err != nil {
		t.Fatalf("real fixture must decode: %v", err)
	}
	for _, tc := range []struct {
		name   string
		suffix string
		ok     bool
	}{
		{"trailing whitespace", " \n\t\r\n", true},
		{"extra closing brace", "}", false},
		{"extra closing bracket", "]", false},
		{"brace after whitespace", "\n}\n", false},
		{"second object", "{}", false},
		{"second copy of the document", string(raw), false},
		{"trailing junk", "x", false},
		{"trailing number", "0", false},
		{"trailing comma", ",", false},
	} {
		doc := append(append([]byte{}, raw...), tc.suffix...)
		_, err := decodeVectors(doc)
		if tc.ok && err != nil {
			t.Errorf("%s: rejected: %v", tc.name, err)
		}
		if !tc.ok && err == nil {
			t.Errorf("%s: accepted invalid document", tc.name)
		}
	}
}

func TestVectorsReaderRefusesUnknownAndMissingFields(t *testing.T) {
	raw, err := os.ReadFile(vectorsPath)
	if err != nil {
		t.Fatalf("shared crypto vectors are required, not optional: %v", err)
	}
	edit := func(f func(m map[string]any)) []byte {
		var m map[string]any
		if err := json.Unmarshal(raw, &m); err != nil {
			t.Fatalf("parse fixture: %v", err)
		}
		f(m)
		b, err := json.Marshal(m)
		if err != nil {
			t.Fatalf("re-encode fixture: %v", err)
		}
		return b
	}
	if _, err := decodeVectors(edit(func(map[string]any) {})); err != nil {
		t.Fatalf("unedited round-trip must decode: %v", err)
	}
	for _, tc := range []struct {
		name string
		f    func(m map[string]any)
	}{
		{"unknown top-level block", func(m map[string]any) { m["newBlock"] = map[string]any{"x": "1"} }},
		{"unknown nested field", func(m map[string]any) { m["aead"].(map[string]any)["tagHex"] = "00" }},
		{"missing top-level string", func(m map[string]any) { delete(m, "sas") }},
		{"missing nested string", func(m map[string]any) { delete(m["textKeys"].(map[string]any), "domain") }},
		{"missing block", func(m map[string]any) { delete(m, "resumeAuth") }},
	} {
		if _, err := decodeVectors(edit(tc.f)); err == nil {
			t.Errorf("%s: accepted", tc.name)
		}
	}
}

func unhex(t *testing.T, name, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("%s is not hex: %v", name, err)
	}
	return b
}

func vectorPair(t *testing.T, name string, kp vectorKeyPair) *KeyPair {
	t.Helper()
	pair, err := KeyPairFromSecret(unhex(t, name+".sec", kp.Sec))
	if err != nil {
		t.Fatalf("%s: KeyPairFromSecret: %v", name, err)
	}
	if got, want := pair.PublicKey(), unhex(t, name+".pub", kp.Pub); !bytes.Equal(got, want) {
		t.Fatalf("%s public key derived from its secret = %x, fixture %x", name, got, want)
	}
	return pair
}

// TestVectorsKeyAgreement: both public keys derive from their secrets, and
// crypto_kx client/server session keys match libsodium in both directions.
func TestVectorsKeyAgreement(t *testing.T) {
	v := loadVectors(t)
	alice := vectorPair(t, "alice", v.Alice)
	bob := vectorPair(t, "bob", v.Bob)

	aliceKeys, err := DeriveSession(Initiator, alice, bob.PublicKey())
	if err != nil {
		t.Fatalf("alice DeriveSession: %v", err)
	}
	bobKeys, err := DeriveSession(Responder, bob, alice.PublicKey())
	if err != nil {
		t.Fatalf("bob DeriveSession: %v", err)
	}
	for _, c := range []struct {
		name string
		got  []byte
		want string
	}{
		{"alice send", aliceKeys.Send(), v.Session.AliceSend},
		{"alice recv", aliceKeys.Recv(), v.Session.AliceRecv},
		{"bob send", bobKeys.Send(), v.Session.BobSend},
		{"bob recv", bobKeys.Recv(), v.Session.BobRecv},
		{"alice resume-auth", aliceKeys.ResumeAuth(), v.ResumeAuth.KeyHex},
		{"bob resume-auth", bobKeys.ResumeAuth(), v.ResumeAuth.KeyHex},
		{"alice text send", aliceKeys.TextSend(), v.TextKeys.AliceTextSend},
		{"alice text recv", aliceKeys.TextRecv(), v.TextKeys.AliceTextRecv},
		{"bob text send", bobKeys.TextSend(), v.TextKeys.BobTextSend},
		{"bob text recv", bobKeys.TextRecv(), v.TextKeys.BobTextRecv},
	} {
		if want := unhex(t, c.name, c.want); !bytes.Equal(c.got, want) {
			t.Errorf("%s = %x, fixture %x", c.name, c.got, want)
		}
	}
	// The fixture's own mirror claims, checked rather than assumed: if the
	// generator ever stopped mirroring, the per-value checks above would still
	// pass against a fixture that no longer describes a working link.
	if !bytes.Equal(aliceKeys.Send(), bobKeys.Recv()) || !bytes.Equal(aliceKeys.Recv(), bobKeys.Send()) {
		t.Error("session keys do not mirror across roles")
	}
	if !bytes.Equal(aliceKeys.TextSend(), bobKeys.TextRecv()) || !bytes.Equal(aliceKeys.TextRecv(), bobKeys.TextSend()) {
		t.Error("text keys do not mirror across roles")
	}
	// Per direction, never collapsed: a sorted derivation would make these equal.
	if bytes.Equal(aliceKeys.TextSend(), aliceKeys.TextRecv()) {
		t.Error("text send and recv keys collapsed onto one value")
	}
}

func TestVectorsTextDomain(t *testing.T) {
	v := loadVectors(t)
	if v.TextKeys.Domain != textKeyDomain {
		t.Fatalf("text domain = %q, fixture %q", textKeyDomain, v.TextKeys.Domain)
	}
	if len(v.TextKeys.Domain) != 17 {
		t.Fatalf("fixture text domain is %d bytes, protocol says 17", len(v.TextKeys.Domain))
	}
}

func TestVectorsSAS(t *testing.T) {
	v := loadVectors(t)
	a := unhex(t, "alice.pub", v.Alice.Pub)
	b := unhex(t, "bob.pub", v.Bob.Pub)
	for _, order := range [][2][]byte{{a, b}, {b, a}} {
		got, err := SAS(order[0], order[1])
		if err != nil {
			t.Fatalf("SAS: %v", err)
		}
		if got != v.SAS {
			t.Errorf("SAS(%x…, %x…) = %q, fixture %q", order[0][:4], order[1][:4], got, v.SAS)
		}
	}
}

func TestVectorsCommit(t *testing.T) {
	v := loadVectors(t)
	pub := unhex(t, "alice.pub", v.Alice.Pub)
	nonce := unhex(t, "commit.nonce", v.Commit.Nonce)
	want := unhex(t, "commit.value", v.Commit.Value)
	got, err := CommitKey(pub, nonce)
	if err != nil {
		t.Fatalf("CommitKey: %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("commit = %x, fixture %x", got, want)
	}
	if !VerifyCommit(want, pub, nonce) {
		t.Fatal("VerifyCommit rejected the fixture commitment")
	}
	for i := range want {
		bad := bytes.Clone(want)
		bad[i] ^= 0x01
		if VerifyCommit(bad, pub, nonce) {
			t.Fatalf("VerifyCommit accepted a commitment with byte %d flipped", i)
		}
	}
	otherNonce := bytes.Clone(nonce)
	otherNonce[31] ^= 0x80
	if VerifyCommit(want, pub, otherNonce) {
		t.Fatal("VerifyCommit accepted the commitment under a different nonce")
	}
	if VerifyCommit(want, unhex(t, "bob.pub", v.Bob.Pub), nonce) {
		t.Fatal("VerifyCommit accepted the commitment for a different public key")
	}
}

func TestVectorsAEAD(t *testing.T) {
	v := loadVectors(t)
	key := unhex(t, "aead.keyHex", v.AEAD.KeyHex)
	pt := unhex(t, "aead.ptHex", v.AEAD.PtHex)
	ct := unhex(t, "aead.ctHex", v.AEAD.CtHex)

	got, err := Seal(key, v.AEAD.Seq, pt)
	if err != nil {
		t.Fatalf("Seal: %v", err)
	}
	if !bytes.Equal(got, ct) {
		t.Fatalf("Seal = %x, fixture %x", got, ct)
	}
	opened, err := Open(key, v.AEAD.Seq, ct)
	if err != nil {
		t.Fatalf("Open fixture ciphertext: %v", err)
	}
	if !bytes.Equal(opened, pt) {
		t.Fatalf("Open = %x, fixture %x", opened, pt)
	}
	// The fixture's seq is small, so it pins the low word only. The other
	// neighbours of the nonce layout fail closed here too.
	for _, seq := range []uint64{v.AEAD.Seq + 1, v.AEAD.Seq << 32, v.AEAD.Seq << 56} {
		if pt, err := Open(key, seq, ct); err == nil || pt != nil {
			t.Errorf("Open under seq %#x succeeded (pt=%x, err=%v)", seq, pt, err)
		}
	}
}

func TestVectorsResumeAuth(t *testing.T) {
	v := loadVectors(t)
	key := unhex(t, "resumeAuth.keyHex", v.ResumeAuth.KeyHex)
	got, err := SignResume(key, v.ResumeAuth.Payload)
	if err != nil {
		t.Fatalf("SignResume: %v", err)
	}
	if got != v.ResumeAuth.MAC {
		t.Fatalf("SignResume = %q, fixture %q", got, v.ResumeAuth.MAC)
	}
	if !VerifyResume(key, v.ResumeAuth.Payload, v.ResumeAuth.MAC) {
		t.Fatal("VerifyResume rejected the fixture tag")
	}
	if VerifyResume(key, v.ResumeAuth.Payload+" ", v.ResumeAuth.MAC) {
		t.Fatal("VerifyResume accepted the fixture tag for a changed payload")
	}
}
