// The BUILT stored-runtime artifact, against frozen cross-platform vectors.
//
// ## Why this does not encrypt and then decrypt with the same code
//
// A round trip through one implementation proves that implementation is
// self-consistent, which is exactly the property a divergent implementation
// also has. So the inputs here are `apps/RelayiumKit/Tests/Fixtures/store-wire-vectors.json`
// — checked in, generated by `web/scripts/gen-store-wire-vectors.mjs` with a
// fixed key, and already consumed by the Swift client. If this bundle's nonce
// schedule, frame layout, base64url alphabet or manifest sanitisation drifted
// from the wire, these bytes stop opening.
//
// What the vectors pin, and each is a separate way to be wrong:
//
//   * `keyB64url` -> the key handle. The fragment alphabet.
//   * `manifest.ctHex` -> names and sizes. Frame 0 at sequence 0.
//   * `manifest.sanitizedNames` -> the SECOND name contains U+202E (RLO), and
//     the decrypted manifest must come back with it stripped. A receiver that
//     skips that step writes `a<RLO>b.txt` to disk.
//   * `streamHex` -> plaintext. Frames at sequence 1, 2, …
//   * `cipherSize` / `plaintextBytes` -> the two totals this app derives itself
//     (`planStoredManifest`), checked against numbers a different language
//     computed.
//
// ## Why the artifact is not built here
//
// `package.json` belongs to another lane, so there is no `pretest` hook to add
// yet. A test that quietly built its own dependency would also hide a broken
// build config behind a passing suite. So the artifact is REQUIRED, and its
// absence fails with the exact command that produces it.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { beforeEach, describe, expect, it } from "vitest";

import { planStoredManifest } from "../../src/main/stored/manifest.js";
import type { StoredRuntime } from "../../src/main/stored/runtime-contract.js";
import {
  StoredRuntimeUnavailableError,
  artifactURL,
  resetStoredRuntimeForTest,
  storedRuntime,
} from "../../src/main/stored/runtime.js";

const ARTIFACT = new URL("../../dist/main/stored-runtime.js", import.meta.url);

const VECTORS = JSON.parse(
  readFileSync(
    fileURLToPath(new URL("../../../RelayiumKit/Tests/Fixtures/store-wire-vectors.json", import.meta.url)),
    "utf8",
  ),
) as {
  keyB64url: string;
  manifest: { json: { files: { name: string; size: number }[] }; ctHex: string; sanitizedNames: string[] };
  files: { name: string; dataHex: string }[];
  streamHex: string;
  cipherSize: number;
  plaintextBytes: number;
};

const fromHex = (hex: string): Uint8Array =>
  new Uint8Array((hex.match(/../g) ?? []).map((byte) => Number.parseInt(byte, 16)));

const utf8 = (bytes: Uint8Array): string => new TextDecoder().decode(bytes);

async function drain(source: AsyncIterable<Uint8Array>): Promise<Uint8Array> {
  const parts: Uint8Array[] = [];
  let total = 0;
  for await (const part of source) {
    parts.push(part);
    total += part.byteLength;
  }
  const out = new Uint8Array(total);
  let at = 0;
  for (const part of parts) {
    out.set(part, at);
    at += part.byteLength;
  }
  return out;
}

/** The built artifact, loaded by explicit path. */
async function built(): Promise<StoredRuntime> {
  resetStoredRuntimeForTest();
  return storedRuntime(async () => {
    try {
      return (await import(ARTIFACT.href)) as { default?: unknown };
    } catch (error) {
      throw new Error(
        `dist/main/stored-runtime.js is missing or unloadable (${(error as Error).message}). ` +
          "Build it from apps/windows: node_modules/.bin/vite build --config vite.stored.config.ts",
      );
    }
  });
}

beforeEach(() => {
  resetStoredRuntimeForTest();
});

describe("artifact location", () => {
  it("resolves one directory UP from the compiled module, not beside it", () => {
    // dist/main/stored/runtime.js -> dist/main/stored-runtime.js
    const compiled = new URL("file:///app/dist/main/stored/runtime.js");
    expect(artifactURL(compiled).href).toBe("file:///app/dist/main/stored-runtime.js");
    // The mistake this pins: `./` would resolve inside dist/main/stored/.
    expect(artifactURL(compiled).href).not.toBe("file:///app/dist/main/stored/stored-runtime.js");
  });
});

describe("loader", () => {
  it("reports a usable failure when the artifact cannot be loaded", async () => {
    const failing = storedRuntime(() => Promise.reject(new Error("ENOENT")));
    await expect(failing).rejects.toBeInstanceOf(StoredRuntimeUnavailableError);
    const message = await failing.catch((error: unknown) => (error as Error).message);
    expect(message).toContain("../stored-runtime.js");
    expect(message).toContain("vite.stored.config.ts");
    // Names the artifact and the build, never a resolved install path.
    expect(message).not.toContain(process.cwd());
  });

  it("refuses an artifact with no default export", async () => {
    await expect(storedRuntime(() => Promise.resolve({}))).rejects.toBeInstanceOf(
      StoredRuntimeUnavailableError,
    );
  });

  it("does not cache a failure, so a transient problem is retryable", async () => {
    await expect(storedRuntime(() => Promise.reject(new Error("boom")))).rejects.toThrow();
    const runtime = await storedRuntime(() => Promise.resolve({ default: { ok: true } }));
    expect(runtime).toEqual({ ok: true });
  });

  it("shares one load between concurrent callers", async () => {
    let loads = 0;
    const load = async (): Promise<{ default?: unknown }> => {
      loads += 1;
      return { default: { ok: true } };
    };
    await Promise.all([storedRuntime(load), storedRuntime(load), storedRuntime(load)]);
    expect(loads).toBe(1);
  });
});

describe("frozen wire vectors", () => {
  it("exposes the wire constants the vectors were generated with", async () => {
    const runtime = await built();
    expect(runtime.constants.storeChunkSize).toBe(192 * 1024);
    expect(runtime.constants.frameOverhead).toBe(4 + 16);
    expect(runtime.constants.maxFrameCiphertext).toBe(192 * 1024 + 16 + 256);
  });

  it("opens the frozen manifest and strips the bidi control character", async () => {
    const runtime = await built();
    const key = await runtime.importKeyFromFragment(VECTORS.keyB64url);
    const manifest = await runtime.decryptManifest(key, fromHex(VECTORS.manifest.ctHex));
    expect(manifest.files.map((file) => file.name)).toEqual(VECTORS.manifest.sanitizedNames);
    expect(manifest.files.map((file) => file.size)).toEqual(
      VECTORS.manifest.json.files.map((file) => file.size),
    );
    // The raw name is what the sender sealed; it must not survive to a caller.
    expect(manifest.files.map((file) => file.name)).not.toContain(VECTORS.manifest.json.files[1]?.name);
  });

  it("agrees with the vectors' own plaintext and ciphertext totals", async () => {
    const runtime = await built();
    const key = await runtime.importKeyFromFragment(VECTORS.keyB64url);
    const manifest = await runtime.decryptManifest(key, fromHex(VECTORS.manifest.ctHex));
    expect(runtime.totalBytes(manifest)).toBe(VECTORS.plaintextBytes);
    // Derived by this app's own arithmetic, checked against a number the
    // generator computed in a different codebase.
    const planned = planStoredManifest(manifest, runtime.constants);
    expect(planned.ok).toBe(true);
    if (!planned.ok) return;
    expect(planned.plan.cipherBytes).toBe(VECTORS.cipherSize);
    expect(planned.plan.cipherBytes).toBe(fromHex(VECTORS.streamHex).byteLength);
    expect(planned.plan.totalBytes).toBe(VECTORS.plaintextBytes);
  });

  it("decrypts the frozen stream delivered as one chunk", async () => {
    const runtime = await built();
    const key = await runtime.importKeyFromFragment(VECTORS.keyB64url);
    const decryptor = runtime.createDecryptor(key);
    const plaintext = await drain(decryptor.push(fromHex(VECTORS.streamHex)));
    expect(utf8(plaintext)).toBe("hello worldxyz");
    await drain(decryptor.end(VECTORS.plaintextBytes));
    expect(decryptor.decryptedBytes).toBe(VECTORS.plaintextBytes);
  });

  it("decrypts the same stream delivered one byte at a time", async () => {
    // The reassembly case that matters: every frame is split across many
    // deliveries, including inside its 4-byte length prefix.
    const runtime = await built();
    const key = await runtime.importKeyFromFragment(VECTORS.keyB64url);
    const decryptor = runtime.createDecryptor(key);
    const stream = fromHex(VECTORS.streamHex);
    const parts: string[] = [];
    for (const byte of stream) {
      parts.push(utf8(await drain(decryptor.push(new Uint8Array([byte])))));
    }
    await drain(decryptor.end(VECTORS.plaintextBytes));
    expect(parts.join("")).toBe("hello worldxyz");
  });

  it("decrypts the same stream split inside the length prefix", async () => {
    const runtime = await built();
    const key = await runtime.importKeyFromFragment(VECTORS.keyB64url);
    const decryptor = runtime.createDecryptor(key);
    const stream = fromHex(VECTORS.streamHex);
    const first = utf8(await drain(decryptor.push(stream.subarray(0, 2))));
    const rest = utf8(await drain(decryptor.push(stream.subarray(2))));
    await drain(decryptor.end(VECTORS.plaintextBytes));
    expect(first + rest).toBe("hello worldxyz");
  });

  it("refuses a stream truncated on a FRAME BOUNDARY", async () => {
    // The whole reason `end` takes an expected length: dropping the second
    // frame entirely leaves no dangling bytes, so nothing about the stream
    // itself says it is incomplete.
    const runtime = await built();
    const key = await runtime.importKeyFromFragment(VECTORS.keyB64url);
    const decryptor = runtime.createDecryptor(key);
    const firstFrameOnly = fromHex(VECTORS.streamHex).subarray(0, 4 + 11 + 16);
    expect(utf8(await drain(decryptor.push(firstFrameOnly)))).toBe("hello world");
    await expect(drain(decryptor.end(VECTORS.plaintextBytes))).rejects.toThrow();
  });

  it("refuses a stream truncated mid-frame", async () => {
    const runtime = await built();
    const key = await runtime.importKeyFromFragment(VECTORS.keyB64url);
    const decryptor = runtime.createDecryptor(key);
    const stream = fromHex(VECTORS.streamHex);
    await drain(decryptor.push(stream.subarray(0, stream.byteLength - 1)));
    await expect(drain(decryptor.end(VECTORS.plaintextBytes))).rejects.toThrow();
  });

  it("refuses a tampered ciphertext frame", async () => {
    const runtime = await built();
    const key = await runtime.importKeyFromFragment(VECTORS.keyB64url);
    const decryptor = runtime.createDecryptor(key);
    const stream = fromHex(VECTORS.streamHex);
    // One bit inside the first frame's ciphertext body.
    const tampered = stream.slice();
    tampered[6] = (tampered[6] ?? 0) ^ 0x01;
    await expect(drain(decryptor.push(tampered))).rejects.toThrow();
  });

  it("refuses a tampered manifest", async () => {
    const runtime = await built();
    const key = await runtime.importKeyFromFragment(VECTORS.keyB64url);
    const sealed = fromHex(VECTORS.manifest.ctHex);
    sealed[0] = (sealed[0] ?? 0) ^ 0x01;
    await expect(runtime.decryptManifest(key, sealed)).rejects.toThrow();
  });

  it("refuses the frozen manifest under a different key", async () => {
    const runtime = await built();
    const other = await runtime.importKeyFromFragment("A".repeat(43));
    await expect(runtime.decryptManifest(other, fromHex(VECTORS.manifest.ctHex))).rejects.toThrow();
  });

  it("refuses a fragment the base64url alphabet does not admit, without quoting it", async () => {
    const runtime = await built();
    for (const bad of ["VVVV+VVV", "VV VV", "VVVVV", "abc="]) {
      const error = await runtime.importKeyFromFragment(bad).then(
        () => null,
        (reason: unknown) => reason as Error,
      );
      expect(error, bad).not.toBeNull();
      expect(error?.message).not.toContain(bad);
    }
  });
});
