package com.relayium.protocol

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * The Android half of the cross-language link-session state-machine vectors
 * (W-N18 A08e): `link-session-vectors.json`, generated by
 * `web/scripts/gen-link-session-vectors.mjs` from the Web authority and gated
 * byte-for-byte by `web/scripts/check-wire-vectors.mjs`. Read-only here.
 *
 * Each scenario drives the REAL [FileLaneSession] / [TextLaneSession]. The
 * other end is a scripted peer sealing with this module's own
 * [RealtimeSender] / [TextWire.Sender] under the peer's real session keys, so
 * the machine's demux and codecs see exactly what a live peer would send. The
 * lane machines are pure and own no timers; a timer step calls the timeout
 * entry point the adapter calls when that bound expires (the fake clock), and
 * a scenario whose timer lives only in the app-module adapter names that in its
 * `skip` instead of being driven here.
 *
 * Divergences recorded for `kotlin` in the fixture are ASSERTED, not skipped:
 * when Android is aligned with the Web, the vector goes red until the entry is
 * removed from the generator.
 */
class LinkSessionVectorTest {

    private val me = "kotlin"

    private val vectors: Json.Obj by lazy {
        val dir = System.getProperty("relayium.fixtures")
            ?: error("relayium.fixtures is not set; protocol/build.gradle.kts points it at the shared fixtures")
        val file = File(dir, "link-session-vectors.json")
        check(file.isFile) { "fixture link-session-vectors.json is missing from $dir" }
        Json.parse(file.readText(Charsets.UTF_8)) as? Json.Obj ?: error("fixture is not a JSON object")
    }

    // ── fixture reading ─────────────────────────────────────────────────────

    private data class Expect(val emit: List<String>, val state: String)
    private data class Planned(val index: Int, val op: String, var expect: Expect, var stopAfter: Boolean = false)

    private fun strings(v: Json?): List<String> = (v as? Json.Arr)?.items?.map { Fixtures.string(it) } ?: emptyList()

    private fun expectOf(o: Json.Obj): Expect {
        val e = o["expect"] as? Json.Obj ?: error("step without expect")
        return Expect(strings(e["emit"]), Fixtures.string(e["state"]))
    }

    private fun name(s: Json.Obj) = Fixtures.string(s["name"])

    private fun consumers(s: Json.Obj) = strings(s["consumers"])

    /** The fixture's `stepSemantics` for this consumer. */
    private fun planFor(s: Json.Obj): List<Planned> {
        val out = ArrayList<Planned>()
        for ((index, raw) in Fixtures.arr(s, "steps").withIndex()) {
            val step = raw as Json.Obj
            val exp = expectOf(step)
            if (me in strings(step["auto"])) {
                val prev = out.lastOrNull() ?: fail("${name(s)}: step $index is auto for kotlin with no previous step")
                prev.expect = Expect(prev.expect.emit + exp.emit, exp.state)
                continue
            }
            out.add(Planned(index, Fixtures.string(step["do"]), exp))
        }
        for (raw in (s["divergences"] as? Json.Arr)?.items ?: emptyList()) {
            val d = raw as Json.Obj
            if (Fixtures.string(d["consumer"]) != me) continue
            val at = Fixtures.number(d["step"]).toInt()
            val p = out.firstOrNull { it.index == at }
                ?: fail("${name(s)}: divergence names step $at, which kotlin does not perform")
            p.expect = expectOf(d)
            p.stopAfter = Fixtures.optionalBool(d["stopAfter"]) ?: false
        }
        return out
    }

    private fun bound(key: String): Long = Fixtures.num(vectors, "bounds", key)

    // ── tokens ──────────────────────────────────────────────────────────────

    private fun fileTokens(actions: List<FileLaneSession.Action>): List<String> =
        actions.filterIsInstance<FileLaneSession.Action.Send>().mapNotNull { a ->
            val f = a.frame
            if (f.size == 1) {
                when (f[0].toInt() and 0xff) {
                    0xfe -> "ACCEPT"; 0xff -> "REJECT"; 0xfd -> "COMPLETE"; 0xf9 -> "BUSY"; 0xf8 -> "BATCH_ABORT"
                    else -> "CTRL(0x${Integer.toHexString(f[0].toInt() and 0xff)})"
                }
            } else {
                when (f[0].toInt() and 0xff) {
                    RealtimeFrame.KIND_BATCH_PART, RealtimeFrame.KIND_CHUNK_PART -> null
                    RealtimeFrame.KIND_BATCH_ENC -> "MANIFEST"
                    RealtimeFrame.KIND_CHUNK -> "CHUNK"
                    RealtimeFrame.KIND_DONE_ENC -> "DONE"
                    RealtimeFrame.KIND_ACK -> "ACK"
                    else -> "KIND(${f[0].toInt() and 0xff})"
                }
            }
        }

    private fun textTokens(actions: List<TextLaneSession.Action>): List<String> =
        actions.filterIsInstance<TextLaneSession.Action.Send>().map { a ->
            val f = a.frame
            if (f.size == 1) {
                when (f[0].toInt() and 0xff) {
                    TextWire.CTRL_REQUEST -> "REQUEST"; 0xfe -> "ACCEPT"; 0xff -> "REJECT"; TextWire.CTRL_END -> "END"
                    else -> "CTRL(0x${Integer.toHexString(f[0].toInt() and 0xff)})"
                }
            } else if ((f[0].toInt() and 0xff) == TextWire.KIND) "MESSAGE" else "KIND(${f[0].toInt() and 0xff})"
        }

    // ── keyed pair ──────────────────────────────────────────────────────────

    private class Keyed(val mine: Crypto.SessionKeys, val peer: Crypto.SessionKeys)

    private fun keyed(role: String): Keyed {
        val a = Crypto.generateKeyPair()
        val b = Crypto.generateKeyPair()
        val (mineRole, peerRole) = when (role) {
            "initiator" -> Crypto.Role.INITIATOR to Crypto.Role.RESPONDER
            "responder" -> Crypto.Role.RESPONDER to Crypto.Role.INITIATOR
            else -> fail("unknown role $role")
        }
        return Keyed(Crypto.deriveSession(mineRole, a, b.publicKey), Crypto.deriveSession(peerRole, b, a.publicKey))
    }

    private val maxFrame = 262_144
    private val peerFile = FileMeta("hello.txt", 5)
    private val body = "hello".toByteArray()

    // ── file lane ───────────────────────────────────────────────────────────

    private fun fileState(s: FileLaneSession): String = when {
        s.sendState == FileLaneSession.SendState.FAILED || s.receiveState == FileLaneSession.ReceiveState.FAILED -> "Ended"
        s.receiveState == FileLaneSession.ReceiveState.PROMPT -> "InPrompt"
        s.receiveState == FileLaneSession.ReceiveState.RECEIVING ||
            s.receiveState == FileLaneSession.ReceiveState.VERIFYING -> "InRecv"
        s.receiveState == FileLaneSession.ReceiveState.DRAINING -> "InDrain"
        s.sendState == FileLaneSession.SendState.WAITING_ACCEPT -> "OutWait"
        s.sendState == FileLaneSession.SendState.SENDING -> "OutSend"
        s.sendState == FileLaneSession.SendState.FINISHING -> "OutFinish"
        else -> "Idle"
    }

    private fun runFile(s: Json.Obj) {
        val k = keyed(Fixtures.string(s["role"]))
        val subject = FileLaneSession(k.mine, maxFrame)
        subject.attachReceiver()
        val peer = RealtimeSender()
        var announced = false
        var contentSent = false
        fun feed(frames: List<ByteArray>) = frames.flatMap { subject.onFrame(it) }
        fun manifest(deliver: Boolean): List<FileLaneSession.Action> {
            val frames = peer.batchFrames(listOf(peerFile), k.peer, maxFrame)
            announced = true
            contentSent = false
            return if (deliver) feed(frames) else emptyList()
        }
        fun content(): List<FileLaneSession.Action> {
            check(announced && !contentSent) { "scripted peer: no content left in the announced batch" }
            contentSent = true
            return feed(peer.chunkFrames(body, k.peer, maxFrame))
        }
        val goodChain = Crypto.chainAdvance(Crypto.chainStart(), body)
        val wrongChain = Crypto.chainAdvance(Crypto.chainStart(), "hellp".toByteArray())

        for (p in planFor(s)) {
            val actions: List<FileLaneSession.Action> = when (p.op) {
                "local:offer" -> subject.startBatch(listOf(FileMeta("out.txt", 5)))
                "local:send-all" -> subject.sendChunk(body) + subject.sendDone(goodChain) + subject.finishSending()
                "local:accept" -> subject.acceptIncoming()
                "local:reject" -> subject.rejectIncoming()
                "local:cancel-in" -> subject.cancelIncoming()
                "local:cancel-out" -> subject.cancelOutgoing()
                "local:durable" -> subject.onDurableBytes(subject.receivedContentBytes)
                "local:commit" ->
                    if (subject.receiveState == FileLaneSession.ReceiveState.VERIFYING) subject.onBatchExported() else emptyList()
                "peer:manifest" -> manifest(true)
                "peer:content" -> content()
                "peer:done" -> feed(listOf(peer.doneFrame(goodChain, k.peer)))
                "peer:done-mismatch" -> feed(listOf(peer.doneFrame(wrongChain, k.peer)))
                "peer:content-unannounced" -> { manifest(false); content() }
                "peer:ACCEPT" -> subject.onFrame(RealtimeFrame.ACCEPT)
                "peer:REJECT" -> subject.onFrame(RealtimeFrame.REJECT)
                "peer:BUSY" -> subject.onFrame(RealtimeFrame.BUSY)
                "peer:BATCH_ABORT" -> subject.onFrame(RealtimeFrame.BATCH_ABORT)
                "peer:COMPLETE" -> subject.onFrame(RealtimeFrame.COMPLETE)
                // The adapter arms this bound and calls the timeout on expiry.
                "timer:fileDrain" -> subject.abortBarrierTimedOut()
                else -> fail("${name(s)}: the Kotlin file consumer cannot map step \"${p.op}\"")
            }
            assertEquals(p.expect, Expect(fileTokens(actions), fileState(subject)), "${name(s)} step ${p.index} (${p.op})")
            if (p.stopAfter) break
        }
    }

    // ── text lane ───────────────────────────────────────────────────────────

    private fun textState(s: TextLaneSession): String = when (s.state) {
        TextLaneSession.State.IDLE -> "Idle"
        TextLaneSession.State.REQUESTED -> "WaitAccept"
        TextLaneSession.State.INCOMING_REQUEST -> "Incoming"
        TextLaneSession.State.OPEN -> "Open"
        TextLaneSession.State.ENDED -> if (s.canRequest) "Idle" else "EndWait"
        TextLaneSession.State.FAILED -> "Failed"
    }

    private fun runText(s: Json.Obj) {
        val role = Fixtures.string(s["role"])
        val k = keyed(role)
        var clock = 1_800_000_000_000L
        val subject = TextLaneSession(k.mine, maxFrame, now = { clock }, initiator = role == "initiator")
        subject.attachReceiver()
        val peer = TextWire.Sender()
        for (p in planFor(s)) {
            clock += 1_000 // one second between steps: well inside the inbound rate budget
            val actions: List<TextLaneSession.Action> = when (p.op) {
                "local:request" -> subject.request()
                "local:accept" -> subject.accept()
                "local:reject" -> subject.reject()
                "local:end" -> subject.end()
                "local:send" -> subject.send("hi there")
                "peer:REQUEST" -> subject.onFrame(TextWire.REQUEST)
                "peer:ACCEPT" -> subject.onFrame(TextWire.ACCEPT)
                "peer:REJECT" -> subject.onFrame(TextWire.REJECT)
                "peer:END" -> subject.onFrame(TextWire.END)
                "peer:message" -> subject.onFrame(peer.frame("from peer", k.peer))
                "peer:unknown" -> subject.onFrame(byteArrayOf(0x0d, 0x00))
                "peer:short9" -> subject.onFrame(byteArrayOf(0x09, 0x00, 0x00))
                "timer:textEndAck" -> { clock += bound("textEndAck"); subject.endBarrierTimedOut() }
                else -> fail("${name(s)}: the Kotlin text consumer cannot map step \"${p.op}\"")
            }
            assertEquals(p.expect, Expect(textTokens(actions), textState(subject)), "${name(s)} step ${p.index} (${p.op})")
            if (p.stopAfter) break
        }
    }

    // ── tests ───────────────────────────────────────────────────────────────

    @Test
    fun `fixture is the format this consumer reads, with the Web as the authority`() {
        assertEquals("relayium-link-session-vectors/1", Fixtures.str(vectors, "format"))
        assertEquals("web", Fixtures.str(vectors, "authority"))
    }

    @Test
    fun `bounds this consumer maps are its own constants`() {
        assertEquals(FileLaneSession.ABORT_BARRIER_TIMEOUT_MS, bound("fileDrain"))
        assertEquals(TextLaneSession.END_ACK_TIMEOUT_MS, bound("textEndAck"))
        assertEquals(LinkProtocol.CAPS_RETRY_INTERVAL_MS, bound("helloInterval"))
    }

    @Test
    fun `every scenario is listed for kotlin or skipped with a reason`() {
        for (lane in listOf("file", "text")) {
            for (raw in Fixtures.arr(vectors, lane)) {
                val s = raw as Json.Obj
                val listed = me in consumers(s)
                val skipped = ((s["skip"] as? Json.Obj)?.get(me) as? Json.Str)?.value?.isNotEmpty() == true
                assertTrue(listed != skipped, "${name(s)}: kotlin must be listed or skipped with a reason")
            }
        }
    }

    @Test
    fun `file lane scenarios`() {
        val run = Fixtures.arr(vectors, "file").map { it as Json.Obj }.filter { me in consumers(it) }
        assertTrue(run.isNotEmpty(), "no file scenario names kotlin: this suite would assert nothing")
        for (s in run) runFile(s)
    }

    @Test
    fun `text lane scenarios`() {
        val run = Fixtures.arr(vectors, "text").map { it as Json.Obj }.filter { me in consumers(it) }
        assertTrue(run.isNotEmpty(), "no text scenario names kotlin: this suite would assert nothing")
        for (s in run) runText(s)
    }

    @Test
    fun `app hello at roster gain`() {
        val model = Fixtures.obj(vectors, "appPeers", "helloAtRosterGain")
        assertTrue(me in consumers(model))
        val carries = Fixtures.str(model, "helloCarries")
        val session = LinkSession("self")
        val caps = strings(session.capsSignal()["caps"])
        assertTrue(carries in caps, "the hello must carry $carries: $caps")
        for ((i, raw) in Fixtures.arr(model, "steps").withIndex()) {
            val st = raw as Json.Obj
            val hello = when (val op = Fixtures.string(st["do"])) {
                "roster" -> session.rosterChanged(strings(st["peers"]))
                "tick" -> session.helloRetryTick()
                "heard" -> { session.didHearFrom(Fixtures.string(st["peer"])); emptyList() }
                else -> fail("cannot map $op")
            }
            assertEquals(strings(Fixtures.obj(st, "expect")["hello"]), hello, "step $i")
        }
    }

    @Test
    fun `app kind latches cli`() {
        val model = Fixtures.obj(vectors, "appPeers", "kindLatchesCli")
        assertTrue(me in consumers(model))
        for (raw in Fixtures.arr(model, "cases")) {
            val c = raw as Json.Obj
            assertEquals(Fixtures.bool(c["cli"]), CliPeerSignal.isHandshake(c["signal"]), "case ${c["signal"]}")
        }
    }
}
