package linkwire

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"reflect"
	"slices"
	"strings"
	"testing"
	"unicode/utf16"
)

// The shared realtime-wire vectors. Generated by
// web/scripts/gen-realtime-wire-vectors.mjs and read — never copied — by the
// Web, Swift and Android suites; this is the Go reader.
//
// The path is relative to this package directory. A missing or unreadable file
// is a FAILURE, never a skip: a vector suite that silently passes without its
// vectors is the gate that cannot fail.
const wireVectorsPath = "../../../apps/RelayiumKit/Tests/Fixtures/realtime-wire-vectors.json"

// ---- the fixture's shape ------------------------------------------------------
//
// Every struct below mirrors the fixture exactly. A field tagged
// `wire:"optional"` may be absent; every other field must be present with this
// exact, case-sensitive key. A pointer field may be JSON null; no other field
// may. json.RawMessage fields are peer-authored signals and are fed, as their
// raw bytes, to the package's untrusted parsers.

type fxPoint struct {
	Index  uint64 `json:"index"`
	Offset uint64 `json:"offset"`
}

type fxManifestFile struct {
	Name string  `json:"name"`
	Size uint64  `json:"size"`
	Path *string `json:"path" wire:"optional"`
}

type fxManifest struct {
	Files []fxManifestFile `json:"files"`
}

type fxFrameShape struct {
	Kind   byte   `json:"kind"`
	Seq    uint64 `json:"seq"`
	Length int    `json:"length"`
}

type fxFrameStream struct {
	Count        int            `json:"count"`
	Frames       []fxFrameShape `json:"frames"`
	StreamSha256 string         `json:"streamSha256"`
}

type fxBody struct {
	Size   int    `json:"size"`
	Seed   uint32 `json:"seed"`
	Sha256 string `json:"sha256"`
}

type fxCaps struct {
	Caps []string `json:"caps"`
}

type fxLifecycleRow struct {
	FrameHex string  `json:"frameHex"`
	Kind     *string `json:"kind"`
	Why      string  `json:"why" wire:"optional"`
}

type fxSignalExpect struct {
	Signal   json.RawMessage `json:"signal"`
	Expected bool            `json:"expected"`
}

type wireVectors struct {
	SessionKeyHex string     `json:"sessionKeyHex"`
	Manifest      fxManifest `json:"manifest"`
	BatchFrameHex string     `json:"batchFrameHex"`
	Files         []struct {
		DataHex string `json:"dataHex"`
	} `json:"files"`
	FrameStreamHex string   `json:"frameStreamHex"`
	FramesHex      []string `json:"framesHex"`
	AckHex         string   `json:"ackHex"`
	ControlHex     struct {
		Accept   string `json:"accept"`
		Reject   string `json:"reject"`
		Complete string `json:"complete"`
	} `json:"controlHex"`
	DoneHashes     []string `json:"doneHashes"`
	SanitizedNames []struct {
		Name string  `json:"name"`
		Path *string `json:"path" wire:"optional"`
	} `json:"sanitizedNames"`
	Text struct {
		Kind     byte   `json:"kind"`
		MaxBytes int    `json:"maxBytes"`
		KeyHex   string `json:"keyHex"`
		Frames   []struct {
			Seq      uint64 `json:"seq"`
			Body     string `json:"body"`
			FrameHex string `json:"frameHex"`
		} `json:"frames"`
	} `json:"text"`
	Kinds struct {
		Chunk       byte `json:"chunk"`
		ChunkPart   byte `json:"chunkPart"`
		BatchEnc    byte `json:"batchEnc"`
		BatchPart   byte `json:"batchPart"`
		ResumeStart byte `json:"resumeStart"`
		ResumeReq   byte `json:"resumeReq"`
		DoneEnc     byte `json:"doneEnc"`
	} `json:"kinds"`
	Limits struct {
		ChunkSize     int `json:"chunkSize"`
		ChunkOverhead int `json:"chunkOverhead"`
		MinPieceBytes int `json:"minPieceBytes"`
	} `json:"limits"`
	Resume struct {
		ReqPoint   fxPoint `json:"reqPoint"`
		ReqFrame   string  `json:"reqFrameHex"`
		StartPoint struct {
			Index  uint64 `json:"index"`
			Offset uint64 `json:"offset"`
			Seq    uint64 `json:"seq"`
		} `json:"startPoint"`
		StartFrame string `json:"startFrameHex"`
	} `json:"resume"`
	Fragmentation struct {
		KeyHex              string        `json:"keyHex"`
		MaxFrameBytes       int64         `json:"maxFrameBytes"`
		PieceBytes          int           `json:"pieceBytes"`
		Manifest            fxManifest    `json:"manifest"`
		Bodies              []fxBody      `json:"bodies"`
		BatchFramesHex      []string      `json:"batchFramesHex"`
		DataFrames          fxFrameStream `json:"dataFrames"`
		LogicalChunkLengths []int         `json:"logicalChunkLengths"`
		DoneHashes          []string      `json:"doneHashes"`
	} `json:"fragmentation"`
	DurableResume struct {
		KeyHex               string        `json:"keyHex"`
		Manifest             fxManifest    `json:"manifest"`
		Body                 fxBody        `json:"body"`
		FirstMaxFrameBytes   int64         `json:"firstMaxFrameBytes"`
		ResumedMaxFrameBytes int64         `json:"resumedMaxFrameBytes"`
		BatchFramesHex       []string      `json:"batchFramesHex"`
		DeliveredFrames      fxFrameStream `json:"deliveredFrames"`
		LostFrames           fxFrameStream `json:"lostFrames"`
		Checkpoint           fxPoint       `json:"checkpoint"`
		ChainAtCheckpointHex string        `json:"chainAtCheckpointHex"`
		ResumeReqHex         string        `json:"resumeReqHex"`
		ResumeStartHex       string        `json:"resumeStartHex"`
		ResumeSeq            uint64        `json:"resumeSeq"`
		ResumedFrames        fxFrameStream `json:"resumedFrames"`
		DoneHashHex          string        `json:"doneHashHex"`
	} `json:"durableResume"`
	MultiFileResume struct {
		KeyHex   string     `json:"keyHex"`
		Manifest fxManifest `json:"manifest"`
		Bodies   []struct {
			Size int    `json:"size"`
			Seed uint32 `json:"seed"`
		} `json:"bodies"`
		MaxFrameBytes int64 `json:"maxFrameBytes"`
		Cases         []struct {
			Point          fxPoint       `json:"point"`
			SeqAtResume    uint64        `json:"seqAtResume"`
			ResumeStartHex string        `json:"resumeStartHex"`
			Frames         fxFrameStream `json:"frames"`
			ResumeReqHex   string        `json:"resumeReqHex"`
		} `json:"cases"`
	} `json:"multiFileResume"`
	Capability fxCapability `json:"capability"`
	Link       fxLink       `json:"link"`
}

type fxCapability struct {
	Hello struct {
		Web              fxCaps `json:"web"`
		Native           fxCaps `json:"native"`
		LinkRoomInactive fxCaps `json:"linkRoomInactive"`
	} `json:"hello"`
	Retry struct {
		Attempts   int `json:"attempts"`
		IntervalMs int `json:"intervalMs"`
	} `json:"retry"`
	SettleSeconds      int `json:"settleSeconds"`
	LastAttemptSeconds int `json:"lastAttemptSeconds"`
	Promotion          []struct {
		Caps                []string `json:"caps"`
		Link                bool     `json:"link"`
		ResolvesImmediately bool     `json:"resolvesImmediately"`
		LegacyLane          string   `json:"legacyLane" wire:"optional"`
	} `json:"promotion"`
	LegacyLane []struct {
		PeerAnnouncesText bool   `json:"peerAnnouncesText"`
		HasArmedBatch     bool   `json:"hasArmedBatch"`
		Lane              string `json:"lane"`
	} `json:"legacyLane"`
	Downgrade struct {
		Text  fxCaps `json:"text"`
		Files fxCaps `json:"files"`
	} `json:"downgrade"`
	Revocation struct {
		First fxCaps `json:"first"`
		Then  fxCaps `json:"then"`
		Link  bool   `json:"link"`
		Text  bool   `json:"text"`
	} `json:"revocation"`
	NotAHello []json.RawMessage `json:"notAHello"`
	Role      []struct {
		Self string `json:"self"`
		Peer string `json:"peer"`
		Role string `json:"role"`
	} `json:"role"`
	ProvenLink struct {
		Signal          json.RawMessage `json:"signal"`
		Caps            []string        `json:"caps"`
		DoesNotOverrule fxCaps          `json:"doesNotOverrule"`
	} `json:"provenLink"`
}

type fxLink struct {
	Capability           string   `json:"capability"`
	ChannelLabels        []string `json:"channelLabels"`
	CaptureMaxBytes      int      `json:"captureMaxBytes"`
	AuthTagLength        int      `json:"authTagLength"`
	HeldSignalMax        int      `json:"heldSignalMax"`
	MaxCandidateProgress int      `json:"maxCandidateProgress"`
	Deadlines            struct {
		NoProgressMs        int `json:"noProgressMs"`
		SetupHardCapMs      int `json:"setupHardCapMs"`
		KeyRevealMs         int `json:"keyRevealMs"`
		HandshakeDeadlineMs int `json:"handshakeDeadlineMs"`
		LinkAuthMs          int `json:"linkAuthMs"`
		LinkRequestMs       int `json:"linkRequestMs"`
		LinkRequestRetryMs  int `json:"linkRequestRetryMs"`
		RecoveryWindowMs    int `json:"recoveryWindowMs"`
		RecoveryRetryMs     int `json:"recoveryRetryMs"`
	} `json:"deadlines"`
	ControlHex struct {
		Accept      string `json:"accept"`
		Reject      string `json:"reject"`
		Complete    string `json:"complete"`
		Busy        string `json:"busy"`
		BatchAbort  string `json:"batchAbort"`
		TextRequest string `json:"textRequest"`
		TextEnd     string `json:"textEnd"`
	} `json:"controlHex"`
	Lifecycle struct {
		File      []fxLifecycleRow `json:"file"`
		Text      []fxLifecycleRow `json:"text"`
		TextFrame []struct {
			FrameHex    string `json:"frameHex"`
			IsTextFrame bool   `json:"isTextFrame"`
			Why         string `json:"why" wire:"optional"`
		} `json:"textFrame"`
	} `json:"lifecycle"`
	FrameClass []struct {
		Label    string `json:"label"`
		FrameHex string `json:"frameHex"`
		Class    string `json:"class"`
		Control  string `json:"control" wire:"optional"`
		Why      string `json:"why" wire:"optional"`
	} `json:"frameClass"`
	AuthPayload []struct {
		Label          string          `json:"label"`
		Signal         json.RawMessage `json:"signal"`
		PayloadUtf8Hex string          `json:"payloadUtf8Hex"`
		PayloadASCII   *string         `json:"payloadAscii" wire:"optional"`
	} `json:"authPayload"`
	LinkLeavePayload []struct {
		Label              string   `json:"label"`
		FromUtf16          []uint16 `json:"fromUtf16"`
		ToUtf16            []uint16 `json:"toUtf16"`
		PayloadUtf8Hex     string   `json:"payloadUtf8Hex"`
		PayloadASCII       *string  `json:"payloadAscii" wire:"optional"`
		SwiftRepresentable *bool    `json:"swiftRepresentable" wire:"optional"`
		Why                string   `json:"why" wire:"optional"`
	} `json:"linkLeavePayload"`
	Leave struct {
		KeyHex      string `json:"keyHex"`
		From        string `json:"from"`
		To          string `json:"to"`
		Payload     string `json:"payload"`
		Tag         string `json:"tag"`
		TagLength   int    `json:"tagLength"`
		ReversedTag string `json:"reversedTag"`
		MaxAttempts int    `json:"maxAttempts"`
		Shapes      []struct {
			Label    string          `json:"label"`
			Signal   json.RawMessage `json:"signal"`
			Accepted bool            `json:"accepted"`
			Verifies *bool           `json:"verifies" wire:"optional"`
			Why      string          `json:"why" wire:"optional"`
		} `json:"shapes"`
	} `json:"leave"`
	Signals struct {
		Request    json.RawMessage `json:"request"`
		Busy       json.RawMessage `json:"busy"`
		Leave      json.RawMessage `json:"leave"`
		Generation []struct {
			Signal     json.RawMessage `json:"signal"`
			Generation string          `json:"generation"`
		} `json:"generation"`
		IsLinkOffer   []fxSignalExpect `json:"isLinkOffer"`
		IsLinkRequest []fxSignalExpect `json:"isLinkRequest"`
	} `json:"signals"`
	Flow struct {
		WindowBytes      int `json:"windowBytes"`
		AckIntervalBytes int `json:"ackIntervalBytes"`
	} `json:"flow"`
	TextSession struct {
		MaxMessages   int `json:"maxMessages"`
		MaxBytes      int `json:"maxBytes"`
		Burst         int `json:"burst"`
		PerSecond     int `json:"perSecond"`
		SendBufferMax int `json:"sendBufferMax"`
		IdleMs        int `json:"idleMs"`
		HistoryMax    int `json:"historyMax"`
	} `json:"textSession"`
	Bounds struct {
		PiecePlainBytes []struct {
			MaxFrameBytes int64  `json:"maxFrameBytes"`
			PieceBytes    *int   `json:"pieceBytes"`
			Why           string `json:"why" wire:"optional"`
		} `json:"piecePlainBytes"`
		TextPlainLimit []struct {
			MaxFrameBytes int64 `json:"maxFrameBytes"`
			Limit         int   `json:"limit"`
		} `json:"textPlainLimit"`
		ManifestCiphertext []struct {
			PayloadBytes int  `json:"payloadBytes"`
			Accepted     bool `json:"accepted"`
		} `json:"manifestCiphertext"`
		ManifestFileCount []struct {
			Count    int    `json:"count"`
			Accepted bool   `json:"accepted"`
			Why      string `json:"why" wire:"optional"`
		} `json:"manifestFileCount"`
		ManifestNameBytes []struct {
			NameBytes int  `json:"nameBytes"`
			Accepted  bool `json:"accepted"`
		} `json:"manifestNameBytes"`
		AdvanceAck []struct {
			Acked     uint64  `json:"acked"`
			Sent      uint64  `json:"sent"`
			Candidate float64 `json:"candidate"`
			Result    uint64  `json:"result"`
			Why       string  `json:"why" wire:"optional"`
		} `json:"advanceAck"`
		ResumePoint []struct {
			Sizes   []uint64 `json:"sizes"`
			Point   fxPoint  `json:"point"`
			Aligned bool     `json:"aligned"`
			InRange bool     `json:"inRange"`
			Why     string   `json:"why" wire:"optional"`
		} `json:"resumePoint"`
	} `json:"bounds"`
}

// ---- the reader ---------------------------------------------------------------

func loadWireVectors(t *testing.T) (wireVectors, []byte) {
	t.Helper()
	raw, err := os.ReadFile(wireVectorsPath)
	if err != nil {
		t.Fatalf("shared realtime-wire vectors are required, not optional: %v", err)
	}
	v, err := decodeWireVectors(raw)
	if err != nil {
		t.Fatalf("%s: %v", wireVectorsPath, err)
	}
	return v, raw
}

// decodeWireVectors reads the fixture strictly. The struct decode alone is not
// enough — encoding/json matches keys case-insensitively and leaves a missing
// or null field at its zero value — so the same bytes are also walked as a
// generic tree and every object's EXACT key set is compared with the struct:
// an unknown key, a missing required key, a case-changed key, a null where the
// field is not nullable, or a value of the wrong JSON type all fail. Anything
// but whitespace after the one document fails too.
func decodeWireVectors(raw []byte) (wireVectors, error) {
	var v wireVectors
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&v); err != nil {
		return v, fmt.Errorf("decode strictly: %w", err)
	}
	// dec.More is false before a stray top-level '}' or ']', so it cannot
	// prove the document ended. Decoding once more must hit io.EOF.
	var extra json.RawMessage
	switch err := dec.Decode(&extra); {
	case err == nil:
		return v, errors.New("trailing data after the vector object: a second JSON value")
	case err != io.EOF:
		return v, fmt.Errorf("trailing data after the vector object: %w", err)
	}
	var tree any
	tdec := json.NewDecoder(bytes.NewReader(raw))
	tdec.UseNumber()
	if err := tdec.Decode(&tree); err != nil {
		return v, err
	}
	if err := checkShape(tree, reflect.TypeOf(v), "vectors"); err != nil {
		return v, err
	}
	return v, nil
}

var rawMessageType = reflect.TypeOf(json.RawMessage(nil))

func checkShape(node any, t reflect.Type, path string) error {
	if t == rawMessageType {
		if node == nil {
			return fmt.Errorf("%s: a signal may not be null", path)
		}
		return nil
	}
	if t.Kind() == reflect.Pointer {
		if node == nil {
			return nil
		}
		return checkShape(node, t.Elem(), path)
	}
	if node == nil {
		return fmt.Errorf("%s: null where a value is required", path)
	}
	switch t.Kind() {
	case reflect.Struct:
		obj, ok := node.(map[string]any)
		if !ok {
			return fmt.Errorf("%s: want an object", path)
		}
		known := map[string]bool{}
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			key, _, _ := strings.Cut(f.Tag.Get("json"), ",")
			known[key] = true
			child, present := obj[key]
			if !present {
				if f.Tag.Get("wire") == "optional" {
					continue
				}
				return fmt.Errorf("%s.%s: required key is missing", path, key)
			}
			if err := checkShape(child, f.Type, path+"."+key); err != nil {
				return err
			}
		}
		for key := range obj {
			if !known[key] {
				return fmt.Errorf("%s: unknown key %q", path, key)
			}
		}
	case reflect.Slice:
		arr, ok := node.([]any)
		if !ok {
			return fmt.Errorf("%s: want an array", path)
		}
		for i, e := range arr {
			if err := checkShape(e, t.Elem(), fmt.Sprintf("%s[%d]", path, i)); err != nil {
				return err
			}
		}
	case reflect.String:
		if _, ok := node.(string); !ok {
			return fmt.Errorf("%s: want a string", path)
		}
	case reflect.Bool:
		if _, ok := node.(bool); !ok {
			return fmt.Errorf("%s: want a boolean", path)
		}
	case reflect.Int, reflect.Int64, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float64:
		if _, ok := node.(json.Number); !ok {
			return fmt.Errorf("%s: want a number", path)
		}
	default:
		return fmt.Errorf("%s: unhandled Go type %s", path, t)
	}
	return nil
}

// The reader is itself a gate, so it is tested against the real fixture bytes
// with in-memory edits; the shared file is never written.
func TestWireVectorsReaderIsStrict(t *testing.T) {
	_, raw := loadWireVectors(t)
	for _, tc := range []struct {
		name string
		edit func(string) string
		ok   bool
	}{
		{"unchanged", func(s string) string { return s }, true},
		{"trailing whitespace", func(s string) string { return s + " \n\t\r\n" }, true},
		{"extra closing brace", func(s string) string { return s + "}" }, false},
		{"extra closing bracket", func(s string) string { return s + "]" }, false},
		{"second object", func(s string) string { return s + "{}" }, false},
		{"trailing junk", func(s string) string { return s + "x" }, false},
		{"unknown top-level key", func(s string) string { return strings.Replace(s, "{", `{"extra":1,`, 1) }, false},
		{"unknown nested key", func(s string) string {
			return strings.Replace(s, `"maxFrameBytes": 65536,`, `"maxFrameBytes": 65536, "extra": 1,`, 1)
		}, false},
		{"missing required key", func(s string) string { return strings.Replace(s, `"ackHex"`, `"ackHexRenamed"`, 1) }, false},
		{"case-changed key", func(s string) string { return strings.Replace(s, `"ackHex"`, `"AckHex"`, 1) }, false},
		{"case-changed nested key", func(s string) string { return strings.Replace(s, `"frameHex"`, `"FrameHex"`, 1) }, false},
		{"null where not nullable", func(s string) string {
			return strings.Replace(s, `"tagLength": 44`, `"tagLength": null`, 1)
		}, false},
		{"wrong type", func(s string) string { return strings.Replace(s, `"tagLength": 44`, `"tagLength": "44"`, 1) }, false},
	} {
		edited := tc.edit(string(raw))
		if tc.name != "unchanged" && edited == string(raw) {
			t.Fatalf("%s: the edit did not apply; the reader test is not testing anything", tc.name)
		}
		_, err := decodeWireVectors([]byte(edited))
		if (err == nil) != tc.ok {
			t.Errorf("%s: err=%v, want ok=%v", tc.name, err, tc.ok)
		}
	}
	// Legitimate empty strings and nulls are data, not decoding accidents.
	v, _ := loadWireVectors(t)
	if v.Link.FrameClass[7].FrameHex != "" || v.Link.Lifecycle.File[5].Kind != nil ||
		v.Link.Bounds.PiecePlainBytes[5].PieceBytes != nil {
		t.Fatal("legitimate empty/null fixture values were not preserved")
	}
}

// Every block of the fixture is either consumed by a named test here or
// explicitly deferred. A block added to the fixture fails this test until it is
// classified; a disposition cannot silently go stale.
func TestWireVectorsCoverageMap(t *testing.T) {
	const (
		consumed = "consumed"
		constant = "constant only: value pinned, behaviour is W-N18 Phase 2a3"
		native   = "not applicable: native legacy-lane field, strictly decoded, no Go lane"
	)
	want := map[string]map[string]string{
		"": {
			"sessionKeyHex": consumed, "manifest": consumed, "batchFrameHex": consumed, "files": consumed,
			"frameStreamHex": consumed, "framesHex": consumed, "ackHex": consumed, "controlHex": consumed,
			"doneHashes": consumed, "sanitizedNames": consumed, "text": consumed, "kinds": consumed,
			"limits": consumed, "resume": consumed, "fragmentation": consumed, "durableResume": consumed,
			"multiFileResume": consumed, "capability": consumed, "link": consumed,
		},
		"capability": {
			"hello": consumed, "retry": constant, "settleSeconds": constant, "lastAttemptSeconds": constant,
			"promotion":  consumed + " (link column); resolvesImmediately/legacyLane: " + native,
			"legacyLane": native, "downgrade": native,
			"revocation": consumed + " (link); revocation.text: " + native,
			"notAHello":  consumed, "role": consumed, "provenLink": consumed,
		},
		"link": {
			"capability": consumed, "channelLabels": consumed, "captureMaxBytes": constant,
			"authTagLength": consumed, "heldSignalMax": constant, "maxCandidateProgress": constant,
			"deadlines": constant, "controlHex": consumed, "lifecycle": consumed, "frameClass": consumed,
			"authPayload": consumed, "linkLeavePayload": consumed + " (one unrepresentable row, see its test)",
			"leave": consumed + " (maxAttempts: " + constant + ")", "signals": consumed, "flow": constant,
			"textSession": constant, "bounds": consumed,
		},
	}
	_, raw := loadWireVectors(t)
	var tree map[string]json.RawMessage
	if err := json.Unmarshal(raw, &tree); err != nil {
		t.Fatal(err)
	}
	blocks := map[string]map[string]json.RawMessage{"": tree}
	for _, name := range []string{"capability", "link"} {
		var b map[string]json.RawMessage
		if err := json.Unmarshal(tree[name], &b); err != nil {
			t.Fatal(err)
		}
		blocks[name] = b
	}
	for block, keys := range blocks {
		got := slices.Sorted(func(yield func(string) bool) {
			for k := range keys {
				if !yield(k) {
					return
				}
			}
		})
		wantKeys := slices.Sorted(func(yield func(string) bool) {
			for k := range want[block] {
				if !yield(k) {
					return
				}
			}
		})
		if !slices.Equal(got, wantKeys) {
			t.Errorf("block %q: fixture keys %v, classified %v", block, got, wantKeys)
		}
	}
}

// ---- helpers ------------------------------------------------------------------

func unhex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}

// content is the generator's xorshift body (gen-realtime-wire-vectors.mjs and
// transfer-fragmentation.test.ts): x ^= x<<13; x ^= x>>17; x ^= x<<5, low byte.
// JavaScript's `>>` is an ARITHMETIC shift of the int32 reading of x, so the
// middle step shifts in copies of the sign bit.
func content(n int, seed uint32) []byte {
	out := make([]byte, n)
	x := seed
	if x == 0 {
		x = 1
	}
	for i := range out {
		x ^= x << 13
		x ^= uint32(int32(x) >> 17)
		x ^= x << 5
		out[i] = byte(x)
	}
	return out
}

func sha256Hex(b []byte) string {
	s := sha256.Sum256(b)
	return hex.EncodeToString(s[:])
}

// chainOf is an INDEPENDENT reading of the chain: SHA-256 over prev || chunk,
// from 32 zero bytes, over ChunkSize pieces of body[:n]. It does not call the
// package's chainStep.
func chainOf(body []byte, n int) []byte {
	h := make([]byte, 32)
	for off := 0; off < n; off += 192 * 1024 {
		d := sha256.New()
		d.Write(h)
		d.Write(body[off:min(off+192*1024, n)])
		h = d.Sum(nil)
	}
	return h
}

func assertStream(t *testing.T, what string, frames [][]byte, want fxFrameStream) {
	t.Helper()
	if len(frames) != want.Count || len(want.Frames) != want.Count {
		t.Fatalf("%s: %d frames, want %d", what, len(frames), want.Count)
	}
	for i, f := range frames {
		got := fxFrameShape{Kind: f[0], Seq: uint64(f[1])<<24 | uint64(f[2])<<16 | uint64(f[3])<<8 | uint64(f[4]), Length: len(f)}
		if got != want.Frames[i] {
			t.Fatalf("%s frame %d: %+v, want %+v", what, i, got, want.Frames[i])
		}
	}
	if got := sha256Hex(bytes.Join(frames, nil)); got != want.StreamSha256 {
		t.Fatalf("%s: stream sha256 %s, want %s", what, got, want.StreamSha256)
	}
}

func metas(m fxManifest) []FileMeta {
	out := make([]FileMeta, len(m.Files))
	for i, f := range m.Files {
		out[i] = FileMeta{Name: f.Name, Size: f.Size}
		if f.Path != nil {
			out[i].Path, out[i].HasPath = *f.Path, true
		}
	}
	return out
}

func mustSender(t *testing.T, keyHex string) *FileSender {
	t.Helper()
	s, err := NewFileSender(unhex(t, keyHex))
	if err != nil {
		t.Fatal(err)
	}
	return s
}

func mustReceiver(t *testing.T, keyHex string) *FileReceiver {
	t.Helper()
	r, err := NewFileReceiver(unhex(t, keyHex))
	if err != nil {
		t.Fatal(err)
	}
	return r
}

func feedAll(t *testing.T, r *FileReceiver, frames [][]byte) []FileEvent {
	t.Helper()
	var out []FileEvent
	for i, f := range frames {
		if c, _ := ClassifyFileFrame(f); c != ClassProtected {
			t.Fatalf("frame %d classifies as %v, not protected", i, c)
		}
		ev, err := r.Feed(f)
		if err != nil {
			t.Fatalf("feed frame %d (kind %d): %v", i, f[0], err)
		}
		out = append(out, ev)
	}
	return out
}

// ---- top level: the unfragmented stream ---------------------------------------

func TestVectorsUnfragmentedStream(t *testing.T) {
	v, _ := loadWireVectors(t)
	files := metas(v.Manifest)
	whole := int64(ChunkSize + ChunkOverhead) // the Web sender's default maxFrameBytes

	s := mustSender(t, v.SessionKeyHex)
	batch, err := s.BatchFrames(files, whole)
	if err != nil {
		t.Fatal(err)
	}
	stream := batch
	for _, f := range v.Files {
		frames, err := s.FileFrames(unhex(t, f.DataHex), 0, whole)
		if err != nil {
			t.Fatal(err)
		}
		stream = append(stream, frames...)
	}
	if len(stream) != len(v.FramesHex) {
		t.Fatalf("%d frames, want %d", len(stream), len(v.FramesHex))
	}
	for i, f := range stream {
		if hex.EncodeToString(f) != v.FramesHex[i] {
			t.Errorf("frame %d differs from framesHex", i)
		}
	}
	if hex.EncodeToString(stream[0]) != v.BatchFrameHex {
		t.Error("batch frame differs from batchFrameHex")
	}
	if hex.EncodeToString(bytes.Join(stream, nil)) != v.FrameStreamHex {
		t.Error("stream differs from frameStreamHex")
	}

	// The receiver, fed the fixture's own bytes.
	r := mustReceiver(t, v.SessionKeyHex)
	var frames [][]byte
	for _, h := range v.FramesHex {
		frames = append(frames, unhex(t, h))
	}
	evs := feedAll(t, r, frames)
	if evs[0].Kind != EventManifest || len(evs[0].Manifest) != len(v.SanitizedNames) {
		t.Fatalf("manifest event %+v", evs[0])
	}
	for i, want := range v.SanitizedNames {
		got := evs[0].Manifest[i]
		if got.Name != want.Name || got.HasPath != (want.Path != nil) || (want.Path != nil && got.Path != *want.Path) {
			t.Errorf("sanitized entry %d = %+v, want %+v", i, got, want)
		}
		if got.Size != v.Manifest.Files[i].Size {
			t.Errorf("entry %d size %d", i, got.Size)
		}
	}
	for i := range v.Files {
		chunk, done := evs[1+2*i], evs[2+2*i]
		if chunk.Kind != EventChunk || hex.EncodeToString(chunk.Chunk) != v.Files[i].DataHex {
			t.Errorf("file %d chunk %+v", i, chunk)
		}
		if done.Kind != EventDone || !done.Verified {
			t.Errorf("file %d not verified", i)
		}
		if got := hex.EncodeToString(chainOf(unhex(t, v.Files[i].DataHex), len(v.Files[i].DataHex)/2)); got != v.DoneHashes[i] {
			t.Errorf("file %d doneHash %s, want %s", i, got, v.DoneHashes[i])
		}
	}

	// ACK and the three original controls.
	ack, err := AckFrame(1048576)
	if err != nil || hex.EncodeToString(ack) != v.AckHex {
		t.Errorf("AckFrame(1048576) = %x, %v; want %s", ack, err, v.AckHex)
	}
	if n, ok := ParseAck(unhex(t, v.AckHex)); !ok || n != 1048576 {
		t.Errorf("ParseAck = %v, %v", n, ok)
	}
	for name, c := range map[string]struct {
		fixture string
		goByte  byte
	}{
		"accept": {v.ControlHex.Accept, CtrlAccept}, "reject": {v.ControlHex.Reject, CtrlReject},
		"complete": {v.ControlHex.Complete, CtrlComplete},
	} {
		if hex.EncodeToString([]byte{c.goByte}) != c.fixture {
			t.Errorf("controlHex.%s = %s, Go %02x", name, c.fixture, c.goByte)
		}
	}
}

func TestVectorsKindsAndLimits(t *testing.T) {
	v, _ := loadWireVectors(t)
	k := v.Kinds
	for name, pair := range map[string][2]byte{
		"chunk": {k.Chunk, KindChunk}, "chunkPart": {k.ChunkPart, KindChunkPart}, "batchEnc": {k.BatchEnc, KindBatchEnc},
		"batchPart": {k.BatchPart, KindBatchPart}, "resumeStart": {k.ResumeStart, KindResumeStart},
		"resumeReq": {k.ResumeReq, KindResumeReq}, "doneEnc": {k.DoneEnc, KindDoneEnc}, "text": {v.Text.Kind, KindText},
	} {
		if pair[0] != pair[1] {
			t.Errorf("kind %s: fixture %d, Go %d", name, pair[0], pair[1])
		}
	}
	if v.Limits.ChunkSize != ChunkSize || v.Limits.ChunkOverhead != ChunkOverhead || v.Limits.MinPieceBytes != MinPieceBytes ||
		v.Text.MaxBytes != TextMaxBytes {
		t.Errorf("limits %+v / text max %d", v.Limits, v.Text.MaxBytes)
	}
}

// ---- text frames --------------------------------------------------------------

func TestVectorsTextFrames(t *testing.T) {
	v, _ := loadWireVectors(t)
	key := unhex(t, v.Text.KeyHex)
	s, err := NewTextSender(key)
	if err != nil {
		t.Fatal(err)
	}
	r, err := NewTextReceiver(key)
	if err != nil {
		t.Fatal(err)
	}
	for i, row := range v.Text.Frames {
		if s.NextSeq() != row.Seq {
			t.Fatalf("row %d: sender at seq %d, fixture %d", i, s.NextSeq(), row.Seq)
		}
		f, err := s.Seal([]byte(row.Body))
		if err != nil {
			t.Fatal(err)
		}
		if hex.EncodeToString(f) != row.FrameHex {
			t.Errorf("row %d: frame differs", i)
		}
		fixture := unhex(t, row.FrameHex)
		if !IsTextFrame(fixture) {
			t.Errorf("row %d: not a text frame", i)
		}
		body, err := r.Open(fixture)
		if err != nil || body != row.Body {
			t.Errorf("row %d: open = %q, %v", i, body, err)
		}
	}
}

// ---- resume control frames ----------------------------------------------------

func TestVectorsResumeFrames(t *testing.T) {
	v, _ := loadWireVectors(t)
	req := ResumePoint(v.Resume.ReqPoint)
	f, err := ResumeReqFrame(req)
	if err != nil || hex.EncodeToString(f) != v.Resume.ReqFrame {
		t.Errorf("ResumeReqFrame = %x, %v", f, err)
	}
	if got, err := ParseResumeReq(unhex(t, v.Resume.ReqFrame)); err != nil || got != req {
		t.Errorf("ParseResumeReq = %+v, %v", got, err)
	}

	sp := v.Resume.StartPoint
	s := mustSender(t, v.SessionKeyHex)
	s.next = sp.Seq // the fixture models a sender already at this sequence
	start, err := s.ResumeStartFrame(ResumePoint{Index: sp.Index, Offset: sp.Offset})
	if err != nil || hex.EncodeToString(start) != v.Resume.StartFrame {
		t.Errorf("ResumeStartFrame = %x, %v", start, err)
	}
	if s.NextSeq() != sp.Seq {
		t.Error("RESUME_START consumed a sequence number")
	}
	got, err := ParseResumeStart(unhex(t, v.Resume.StartFrame))
	if err != nil || got != (ResumeStart{Point: ResumePoint{Index: sp.Index, Offset: sp.Offset}, Seq: sp.Seq}) {
		t.Errorf("ParseResumeStart = %+v, %v", got, err)
	}
}

// ---- fragmentation over a 64 KiB peer -----------------------------------------

func TestVectorsFragmentation(t *testing.T) {
	v, _ := loadWireVectors(t)
	fr := v.Fragmentation
	if pb, err := PiecePlainBytes(fr.MaxFrameBytes); err != nil || pb != fr.PieceBytes {
		t.Fatalf("PiecePlainBytes(%d) = %d, %v", fr.MaxFrameBytes, pb, err)
	}
	var bodies [][]byte
	for i, b := range fr.Bodies {
		body := content(b.Size, b.Seed)
		if sha256Hex(body) != b.Sha256 {
			t.Fatalf("body %d: generator mismatch", i)
		}
		bodies = append(bodies, body)
	}

	s := mustSender(t, fr.KeyHex)
	batch, err := s.BatchFrames(metas(fr.Manifest), fr.MaxFrameBytes)
	if err != nil {
		t.Fatal(err)
	}
	if len(batch) != len(fr.BatchFramesHex) {
		t.Fatalf("%d batch frames", len(batch))
	}
	for i := range batch {
		if hex.EncodeToString(batch[i]) != fr.BatchFramesHex[i] {
			t.Errorf("batch frame %d differs", i)
		}
	}
	data, err := s.DataFrames(bodies, nil, fr.MaxFrameBytes)
	if err != nil {
		t.Fatal(err)
	}
	assertStream(t, "fragmentation", data, fr.DataFrames)

	r := mustReceiver(t, fr.KeyHex)
	evs := feedAll(t, r, append(batch, data...))
	var chunkLens []int
	var reassembled [][]byte
	file := 0
	var cur []byte
	for _, ev := range evs {
		switch ev.Kind {
		case EventManifest:
			if len(ev.Manifest) != len(fr.Manifest.Files) {
				t.Fatal("manifest")
			}
		case EventChunk:
			chunkLens = append(chunkLens, len(ev.Chunk))
			cur = append(cur, ev.Chunk...)
		case EventDone:
			if !ev.Verified {
				t.Errorf("file %d not verified", file)
			}
			if got := hex.EncodeToString(chainOf(bodies[file], len(bodies[file]))); got != fr.DoneHashes[file] {
				t.Errorf("file %d doneHash %s", file, got)
			}
			reassembled = append(reassembled, cur)
			cur = nil
			file++
		}
	}
	if !slices.Equal(chunkLens, fr.LogicalChunkLengths) {
		t.Errorf("logical chunks %v, want %v", chunkLens, fr.LogicalChunkLengths)
	}
	for i := range bodies {
		if !bytes.Equal(reassembled[i], bodies[i]) {
			t.Errorf("file %d reassembled wrongly", i)
		}
	}
}

// ---- durable resume across a change of message size ---------------------------

func TestVectorsDurableResume(t *testing.T) {
	v, _ := loadWireVectors(t)
	dr := v.DurableResume
	body := content(dr.Body.Size, dr.Body.Seed)
	if sha256Hex(body) != dr.Body.Sha256 {
		t.Fatal("generator mismatch")
	}
	s := mustSender(t, dr.KeyHex)
	batch, err := s.BatchFrames(metas(dr.Manifest), dr.FirstMaxFrameBytes)
	if err != nil || len(batch) != len(dr.BatchFramesHex) || hex.EncodeToString(batch[0]) != dr.BatchFramesHex[0] {
		t.Fatalf("batch: %v", err)
	}
	first, err := s.DataFrames([][]byte{body}, nil, dr.FirstMaxFrameBytes)
	if err != nil {
		t.Fatal(err)
	}
	delivered, lost := first[:dr.DeliveredFrames.Count], first[dr.DeliveredFrames.Count:]
	assertStream(t, "delivered", delivered, dr.DeliveredFrames)
	assertStream(t, "lost", lost, dr.LostFrames)

	// The receiver durably holds two logical chunks when the transport dies.
	r := mustReceiver(t, dr.KeyHex)
	feedAll(t, r, append(batch, delivered...))
	chain := r.SnapshotChain()
	if hex.EncodeToString(chain[:]) != dr.ChainAtCheckpointHex {
		t.Fatalf("chain at checkpoint %x", chain)
	}
	if got := hex.EncodeToString(chainOf(body, int(dr.Checkpoint.Offset))); got != dr.ChainAtCheckpointHex {
		t.Fatalf("independent chain %s", got)
	}
	cp := ResumePoint(dr.Checkpoint)
	req, err := ResumeReqFrame(cp)
	if err != nil || hex.EncodeToString(req) != dr.ResumeReqHex {
		t.Errorf("resume request %x", req)
	}
	if got, err := ParseResumeReq(req); err != nil || got != cp {
		t.Errorf("ParseResumeReq %+v %v", got, err)
	}

	// The SAME sender, its counter never rewound, refragments for 64 KiB.
	start, err := s.ResumeStartFrame(cp)
	if err != nil || hex.EncodeToString(start) != dr.ResumeStartHex || s.NextSeq() != dr.ResumeSeq {
		t.Fatalf("resume start %x seq %d: %v", start, s.NextSeq(), err)
	}
	resumed, err := s.DataFrames([][]byte{body}, &cp, dr.ResumedMaxFrameBytes)
	if err != nil {
		t.Fatal(err)
	}
	assertStream(t, "resumed", resumed, dr.ResumedFrames)

	rs, err := ParseResumeStart(unhex(t, dr.ResumeStartHex))
	if err != nil || rs.Point != cp || rs.Seq != dr.ResumeSeq {
		t.Fatalf("ParseResumeStart %+v %v", rs, err)
	}
	if err := r.ResumeAt(chain[:], rs.Seq); err != nil {
		t.Fatal(err)
	}
	var tail []byte
	for _, ev := range feedAll(t, r, resumed) {
		switch ev.Kind {
		case EventChunk:
			tail = append(tail, ev.Chunk...)
		case EventDone:
			if !ev.Verified {
				t.Error("resumed file not verified")
			}
		}
	}
	if !bytes.Equal(tail, body[cp.Offset:]) {
		t.Error("resumed bytes differ from the body after the checkpoint")
	}
	if got := hex.EncodeToString(chainOf(body, len(body))); got != dr.DoneHashHex {
		t.Errorf("done hash %s", got)
	}
}

// ---- multi-file checkpoints ---------------------------------------------------

func TestVectorsMultiFileResume(t *testing.T) {
	v, _ := loadWireVectors(t)
	mf := v.MultiFileResume
	var bodies [][]byte
	for _, b := range mf.Bodies {
		bodies = append(bodies, content(b.Size, b.Seed))
	}
	for ci, c := range mf.Cases {
		t.Run(fmt.Sprint(ci), func(t *testing.T) {
			p := ResumePoint(c.Point)
			s := mustSender(t, mf.KeyHex)
			// The fixture models a sender whose counter continues from wherever
			// attempt 1 left it, as a fixed non-zero start.
			s.next = c.SeqAtResume
			start, err := s.ResumeStartFrame(p)
			if err != nil || hex.EncodeToString(start) != c.ResumeStartHex || s.NextSeq() != c.SeqAtResume {
				t.Fatalf("resume start %x: %v", start, err)
			}
			frames, err := s.DataFrames(bodies, &p, mf.MaxFrameBytes)
			if err != nil {
				t.Fatal(err)
			}
			assertStream(t, "case", frames, c.Frames)
			req, err := ResumeReqFrame(p)
			if err != nil || hex.EncodeToString(req) != c.ResumeReqHex {
				t.Errorf("resume request %x", req)
			}

			// A receiver restored to the same checkpoint verifies every DONE.
			r := mustReceiver(t, mf.KeyHex)
			if err := r.ResumeAt(chainOf(bodies[p.Index], int(p.Offset)), c.SeqAtResume); err != nil {
				t.Fatal(err)
			}
			file, got := p.Index, []byte{}
			for _, ev := range feedAll(t, r, frames) {
				switch ev.Kind {
				case EventChunk:
					got = append(got, ev.Chunk...)
				case EventDone:
					from := uint64(0)
					if file == p.Index {
						from = p.Offset
					}
					if !ev.Verified || !bytes.Equal(got, bodies[file][from:]) {
						t.Errorf("file %d: verified=%v, bytes match=%v", file, ev.Verified, bytes.Equal(got, bodies[file][from:]))
					}
					file, got = file+1, []byte{}
				}
			}
			if file != uint64(len(bodies)) {
				t.Errorf("ended at file %d", file)
			}
		})
	}
}

// ---- capability block ---------------------------------------------------------

func mustSignal(t *testing.T, raw []byte) Signal {
	t.Helper()
	s, err := ParseSignal(raw)
	if err != nil {
		t.Fatalf("ParseSignal(%s): %v", raw, err)
	}
	return s
}

func capsSignal(t *testing.T, caps []string) Signal {
	t.Helper()
	raw, err := json.Marshal(map[string][]string{"caps": caps})
	if err != nil {
		t.Fatal(err)
	}
	return mustSignal(t, raw)
}

func TestVectorsCapability(t *testing.T) {
	v, _ := loadWireVectors(t)
	c := v.Capability

	// The hellos are parser inputs here: this package builds none.
	for name, h := range map[string]fxCaps{"web": c.Hello.Web, "native": c.Hello.Native, "linkRoomInactive": c.Hello.LinkRoomInactive} {
		caps, ok := ParseHello(capsSignal(t, h.Caps))
		if !ok || !slices.Equal(caps, h.Caps) {
			t.Errorf("hello %s parsed as %v, %v", name, caps, ok)
		}
		if CapsIncludeLink(caps) != (name != "linkRoomInactive") {
			t.Errorf("hello %s link support wrong", name)
		}
	}
	// Constants only; the cadence itself is W-N18 Phase 2a3.
	if c.Retry.Attempts != CapsAnnounceAttempts || c.Retry.IntervalMs != CapsRetryIntervalMs ||
		c.SettleSeconds != CapsSettleSeconds ||
		c.LastAttemptSeconds*1000 != (CapsAnnounceAttempts-1)*CapsRetryIntervalMs {
		t.Errorf("cadence constants differ: %+v", c.Retry)
	}
	for i, row := range c.Promotion {
		if CapsIncludeLink(row.Caps) != row.Link {
			t.Errorf("promotion %d %v: link=%v", i, row.Caps, row.Link)
		}
	}
	reg := NewPeerCaps()
	reg.Record("p", capsSignal(t, c.Revocation.First.Caps))
	if !reg.SupportsLink("p") {
		t.Fatal("first hello names link/1")
	}
	reg.Record("p", capsSignal(t, c.Revocation.Then.Caps))
	if reg.SupportsLink("p") != c.Revocation.Link {
		t.Error("a later snapshot must revoke link/1")
	}

	for i, raw := range c.NotAHello {
		reg := NewPeerCaps()
		reg.Record("p", capsSignal(t, []string{Capability}))
		s := mustSignal(t, raw)
		if _, ok := ParseHello(s); ok {
			t.Errorf("notAHello %d parsed as a hello", i)
		}
		if reg.Record("p", s) || !reg.SupportsLink("p") {
			t.Errorf("notAHello %d disturbed the earlier announcement", i)
		}
	}
	for i, row := range c.Role {
		want := map[string]string{"initiator": "initiator", "responder": "responder"}[row.Role]
		if got := LinkRole(row.Self, row.Peer).String(); got != want {
			t.Errorf("role %d: %s, want %s", i, got, row.Role)
		}
	}

	pl := c.ProvenLink
	signal := mustSignal(t, pl.Signal)
	silent := NewPeerCaps()
	if silent.Record("p", signal) {
		t.Error("an establishment frame is not a hello")
	}
	if !silent.RecordProvenLink("p", signal) {
		t.Error("a link frame must stand in for a silent peer's hello")
	}
	if got, _ := silent.Announced("p"); !slices.Equal(got, pl.Caps) || !silent.SupportsLink("p") {
		t.Errorf("proven announcement %v", got)
	}
	stated := NewPeerCaps()
	stated.Record("p", capsSignal(t, pl.DoesNotOverrule.Caps))
	if stated.RecordProvenLink("p", signal) || stated.SupportsLink("p") {
		t.Error("a link frame overruled a stated announcement")
	}
}

// ---- link block ---------------------------------------------------------------

func TestVectorsLinkConstants(t *testing.T) {
	v, _ := loadWireVectors(t)
	l := v.Link
	if l.Capability != Capability || !slices.Equal(l.ChannelLabels, ChannelLabels[:]) || l.AuthTagLength != LinkAuthTagLength {
		t.Errorf("capability %q labels %v tag %d", l.Capability, l.ChannelLabels, l.AuthTagLength)
	}
	// Values only. Nothing in this package enforces them.
	d := l.Deadlines
	for name, pair := range map[string][2]int{
		"captureMaxBytes": {l.CaptureMaxBytes, CaptureMaxBytes}, "heldSignalMax": {l.HeldSignalMax, HeldSignalMax},
		"maxCandidateProgress": {l.MaxCandidateProgress, MaxCandidateProgress},
		"noProgressMs":         {d.NoProgressMs, NoProgressMs}, "setupHardCapMs": {d.SetupHardCapMs, SetupHardCapMs},
		"keyRevealMs": {d.KeyRevealMs, KeyRevealMs}, "handshakeDeadlineMs": {d.HandshakeDeadlineMs, HandshakeDeadlineMs},
		"linkAuthMs": {d.LinkAuthMs, LinkAuthMs}, "linkRequestMs": {d.LinkRequestMs, LinkRequestMs},
		"linkRequestRetryMs": {d.LinkRequestRetryMs, LinkRequestRetryMs}, "recoveryWindowMs": {d.RecoveryWindowMs, RecoveryWindowMs},
		"recoveryRetryMs":  {d.RecoveryRetryMs, RecoveryRetryMs},
		"flow.windowBytes": {l.Flow.WindowBytes, FlowWindowBytes}, "flow.ackIntervalBytes": {l.Flow.AckIntervalBytes, FlowAckIntervalBytes},
		"textSession.maxMessages": {l.TextSession.MaxMessages, TextSessionMaxMessages},
		"textSession.maxBytes":    {l.TextSession.MaxBytes, TextSessionMaxBytes},
		"textSession.burst":       {l.TextSession.Burst, TextRateBurst}, "textSession.perSecond": {l.TextSession.PerSecond, TextRatePerSecond},
		"textSession.sendBufferMax": {l.TextSession.SendBufferMax, TextSendBufferMax},
		"textSession.idleMs":        {l.TextSession.IdleMs, TextIdleMs}, "textSession.historyMax": {l.TextSession.HistoryMax, TextHistoryMax},
		"leave.maxAttempts": {l.Leave.MaxAttempts, LeaveMaxAttempts},
	} {
		if pair[0] != pair[1] {
			t.Errorf("%s: fixture %d, Go %d", name, pair[0], pair[1])
		}
	}
	ch := l.ControlHex
	for name, c := range map[string]struct {
		fixture string
		goByte  byte
	}{
		"accept": {ch.Accept, CtrlAccept}, "reject": {ch.Reject, CtrlReject}, "complete": {ch.Complete, CtrlComplete},
		"busy": {ch.Busy, CtrlBusy}, "batchAbort": {ch.BatchAbort, CtrlBatchAbort},
		"textRequest": {ch.TextRequest, CtrlTextRequest}, "textEnd": {ch.TextEnd, CtrlTextEnd},
	} {
		if hex.EncodeToString([]byte{c.goByte}) != c.fixture {
			t.Errorf("controlHex.%s = %s, Go %02x", name, c.fixture, c.goByte)
		}
	}
}

func TestVectorsLinkLifecycleAndFrameClass(t *testing.T) {
	v, _ := loadWireVectors(t)
	lc := v.Link.Lifecycle
	for i, row := range lc.File {
		c, ok := FileLifecycle(unhex(t, row.FrameHex))
		if ok != (row.Kind != nil) || (ok && c.String() != *row.Kind) {
			t.Errorf("file lifecycle %d (%s): %v %v", i, row.FrameHex, c, ok)
		}
	}
	for i, row := range lc.Text {
		c, ok := TextLifecycle(unhex(t, row.FrameHex))
		if ok != (row.Kind != nil) || (ok && c.String() != *row.Kind) {
			t.Errorf("text lifecycle %d (%s): %v %v", i, row.FrameHex, c, ok)
		}
	}
	for i, row := range lc.TextFrame {
		if IsTextFrame(unhex(t, row.FrameHex)) != row.IsTextFrame {
			t.Errorf("textFrame %d: want %v", i, row.IsTextFrame)
		}
	}
	for _, row := range v.Link.FrameClass {
		class, control := ClassifyFileFrame(unhex(t, row.FrameHex))
		if class.String() != row.Class {
			t.Errorf("%s: class %s, want %s", row.Label, class, row.Class)
		}
		if row.Control != "" && control.String() != row.Control {
			t.Errorf("%s: control %s, want %s", row.Label, control, row.Control)
		}
		if row.Control == "" && class == ClassLifecycle {
			t.Errorf("%s: lifecycle row without a control", row.Label)
		}
	}
}

func TestVectorsLinkAuthPayload(t *testing.T) {
	v, _ := loadWireVectors(t)
	for _, row := range v.Link.AuthPayload {
		f, err := AuthFieldsOf(mustSignal(t, row.Signal))
		if err != nil {
			t.Errorf("%s: %v", row.Label, err)
			continue
		}
		p, err := AuthPayload(f)
		if err != nil || hex.EncodeToString([]byte(p)) != row.PayloadUtf8Hex {
			t.Errorf("%s: payload %q, %v", row.Label, p, err)
		}
		if (row.PayloadASCII != nil) != isASCIIString(p) || (row.PayloadASCII != nil && *row.PayloadASCII != p) {
			t.Errorf("%s: payloadAscii disagrees", row.Label)
		}
	}
}

func isASCIIString(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] >= 0x80 {
			return false
		}
	}
	return true
}

func TestVectorsLinkLeavePayload(t *testing.T) {
	v, _ := loadWireVectors(t)
	skipped := 0
	for _, row := range v.Link.LinkLeavePayload {
		from, to := utf16.Decode(row.FromUtf16), utf16.Decode(row.ToUtf16)
		if hasLoneSurrogate(row.FromUtf16) || hasLoneSurrogate(row.ToUtf16) {
			// A Go string is UTF-8 and cannot hold a lone UTF-16 surrogate.
			// Exactly one row is allowed to be unrepresentable, and only this
			// one, flagged as such by the fixture itself.
			if row.Label != "unpaired high surrogate" || row.SwiftRepresentable == nil || *row.SwiftRepresentable {
				t.Errorf("%s: an unrepresentable row that is not the flagged one", row.Label)
			}
			skipped++
			continue
		}
		p, err := LinkLeavePayload(string(from), string(to))
		if err != nil || hex.EncodeToString([]byte(p)) != row.PayloadUtf8Hex {
			t.Errorf("%s: payload %q, %v", row.Label, p, err)
		}
		if (row.PayloadASCII != nil) != isASCIIString(p) || (row.PayloadASCII != nil && *row.PayloadASCII != p) {
			t.Errorf("%s: payloadAscii disagrees", row.Label)
		}
	}
	if skipped != 1 {
		t.Errorf("skipped %d unrepresentable rows, want exactly 1", skipped)
	}
}

func hasLoneSurrogate(u []uint16) bool {
	for i := 0; i < len(u); i++ {
		switch {
		case u[i] >= 0xD800 && u[i] <= 0xDBFF:
			if i+1 >= len(u) || u[i+1] < 0xDC00 || u[i+1] > 0xDFFF {
				return true
			}
			i++
		case u[i] >= 0xDC00 && u[i] <= 0xDFFF:
			return true
		}
	}
	return false
}

func TestVectorsLinkLeave(t *testing.T) {
	v, _ := loadWireVectors(t)
	lv := v.Link.Leave
	key := unhex(t, lv.KeyHex)
	if p, err := LinkLeavePayload(lv.From, lv.To); err != nil || p != lv.Payload {
		t.Errorf("payload %q", p)
	}
	tag, err := SignLeave(key, lv.From, lv.To)
	if err != nil || tag != lv.Tag || len(tag) != lv.TagLength || lv.TagLength != LinkAuthTagLength {
		t.Errorf("SignLeave = %q, %v", tag, err)
	}
	if !VerifyLeave(key, lv.From, lv.To, lv.Tag) {
		t.Error("the genuine leave does not verify")
	}
	if rev, _ := SignLeave(key, lv.To, lv.From); rev != lv.ReversedTag {
		t.Errorf("reversed tag %q", rev)
	}
	if VerifyLeave(key, lv.From, lv.To, lv.ReversedTag) {
		t.Error("a reflected leave verified")
	}
	for _, row := range lv.Shapes {
		auth, ok := LeaveAuth(mustSignal(t, row.Signal))
		if ok != row.Accepted {
			t.Errorf("%s: shape accepted=%v, want %v", row.Label, ok, row.Accepted)
			continue
		}
		if !ok {
			continue
		}
		want := row.Verifies == nil || *row.Verifies
		if VerifyLeave(key, lv.From, lv.To, auth) != want {
			t.Errorf("%s: verifies != %v", row.Label, want)
		}
	}
}

func compact(t *testing.T, raw []byte) string {
	t.Helper()
	var b bytes.Buffer
	if err := json.Compact(&b, raw); err != nil {
		t.Fatal(err)
	}
	return b.String()
}

func TestVectorsLinkSignals(t *testing.T) {
	v, _ := loadWireVectors(t)
	sg := v.Link.Signals
	leave, err := LeaveSignal(v.Link.Leave.Tag)
	if err != nil {
		t.Fatal(err)
	}
	for name, pair := range map[string][2]string{
		"request": {string(RequestSignal()), compact(t, sg.Request)},
		"busy":    {string(BusySignal()), compact(t, sg.Busy)},
		"leave":   {string(leave), compact(t, sg.Leave)},
	} {
		if pair[0] != pair[1] {
			t.Errorf("%s signal %s, fixture %s", name, pair[0], pair[1])
		}
	}
	if !IsLinkRequest(mustSignal(t, RequestSignal())) || SignalGeneration(mustSignal(t, BusySignal())) != GenerationLink {
		t.Error("constructed signals do not classify as themselves")
	}
	if _, ok := LeaveAuth(mustSignal(t, leave)); !ok {
		t.Error("the constructed leave is not a leave")
	}
	for i, row := range sg.Generation {
		if got := SignalGeneration(mustSignal(t, row.Signal)).String(); got != row.Generation {
			t.Errorf("generation %d %s: %s, want %s", i, row.Signal, got, row.Generation)
		}
	}
	for i, row := range sg.IsLinkOffer {
		if IsLinkOffer(mustSignal(t, row.Signal)) != row.Expected {
			t.Errorf("isLinkOffer %d %s: want %v", i, row.Signal, row.Expected)
		}
	}
	for i, row := range sg.IsLinkRequest {
		if IsLinkRequest(mustSignal(t, row.Signal)) != row.Expected {
			t.Errorf("isLinkRequest %d %s: want %v", i, row.Signal, row.Expected)
		}
	}
}

// ---- bounds -------------------------------------------------------------------

// manifestOfPayload builds a manifest whose encoded plaintext is exactly n
// bytes, from ASCII names of 1..MaxNameBytes. An entry with a name of L bytes
// and size 0 encodes as {"name":"…","size":0}, L+20 bytes; entries are joined
// by commas inside {"files":[…]}, 12 bytes.
func manifestOfPayload(t *testing.T, n int) []FileMeta {
	t.Helper()
	k := (n - 12 + 1 + (MaxNameBytes + 21) - 1) / (MaxNameBytes + 21)
	names := n - 12 - (k - 1) - 20*k
	files := make([]FileMeta, k)
	for i := range files {
		l := min(names-(k-1-i), MaxNameBytes)
		files[i] = FileMeta{Name: strings.Repeat("x", l)}
		names -= l
	}
	b, err := EncodeManifest(files)
	if err != nil || len(b) != n || names != 0 {
		t.Fatalf("built a %d-byte manifest, want %d: %v", len(b), n, err)
	}
	return files
}

func TestVectorsLinkBounds(t *testing.T) {
	v, _ := loadWireVectors(t)
	b := v.Link.Bounds
	for _, row := range b.PiecePlainBytes {
		pb, err := PiecePlainBytes(row.MaxFrameBytes)
		if row.PieceBytes == nil {
			if !errors.Is(err, ErrPieceTooSmall) {
				t.Errorf("PiecePlainBytes(%d) = %d, want refusal", row.MaxFrameBytes, pb)
			}
		} else if err != nil || pb != *row.PieceBytes {
			t.Errorf("PiecePlainBytes(%d) = %d, %v; want %d", row.MaxFrameBytes, pb, err, *row.PieceBytes)
		}
	}
	for _, row := range b.TextPlainLimit {
		if got := TextPlainLimit(row.MaxFrameBytes); got != row.Limit {
			t.Errorf("TextPlainLimit(%d) = %d, want %d", row.MaxFrameBytes, got, row.Limit)
		}
	}
	for _, row := range b.ManifestCiphertext {
		files := manifestOfPayload(t, row.PayloadBytes)
		s := mustSender(t, v.SessionKeyHex)
		frames, err := s.BatchFrames(files, 262144)
		if (err == nil) != row.Accepted {
			t.Errorf("manifest payload %d: err=%v, want accepted=%v", row.PayloadBytes, err, row.Accepted)
		}
		if err != nil && (s.NextSeq() != 0 || frames != nil) {
			t.Errorf("manifest payload %d: a refused manifest spent a sequence number", row.PayloadBytes)
		}
	}
	for _, row := range b.ManifestFileCount {
		files := make([]FileMeta, row.Count)
		for i := range files {
			files[i] = FileMeta{Name: "f", Size: 1}
		}
		_, encErr := EncodeManifest(files)
		plain := `{"files":[` + strings.TrimSuffix(strings.Repeat(`{"name":"f","size":1},`, row.Count), ",") + `]}`
		_, decErr := DecodeManifest([]byte(plain))
		if (encErr == nil) != row.Accepted || (decErr == nil) != row.Accepted {
			t.Errorf("file count %d: encode %v decode %v, want accepted=%v", row.Count, encErr, decErr, row.Accepted)
		}
	}
	for _, row := range b.ManifestNameBytes {
		name := strings.Repeat("n", row.NameBytes)
		_, encErr := EncodeManifest([]FileMeta{{Name: name}})
		_, decErr := DecodeManifest([]byte(`{"files":[{"name":"` + name + `","size":0}]}`))
		pathBody := `{"files":[{"name":"n","size":0,"path":"` + name + `"}]}`
		_, pathErr := DecodeManifest([]byte(pathBody))
		if (encErr == nil) != row.Accepted || (decErr == nil) != row.Accepted {
			t.Errorf("name bytes %d: encode %v decode %v, want accepted=%v", row.NameBytes, encErr, decErr, row.Accepted)
		}
		// A path shares the byte bound but may be empty.
		if (pathErr == nil) != (row.NameBytes <= MaxNameBytes) {
			t.Errorf("path bytes %d: %v", row.NameBytes, pathErr)
		}
	}
	for _, row := range b.AdvanceAck {
		if got := AdvanceAck(row.Acked, row.Sent, row.Candidate); got != row.Result {
			t.Errorf("AdvanceAck(%d, %d, %v) = %d, want %d", row.Acked, row.Sent, row.Candidate, got, row.Result)
		}
	}
	for i, row := range b.ResumePoint {
		p := ResumePoint(row.Point)
		if ResumeAligned(p, row.Sizes) != row.Aligned || ResumeInRange(p, row.Sizes) != row.InRange {
			t.Errorf("resume point %d %+v in %v", i, p, row.Sizes)
		}
	}
}
