package linksession

// The Go half of the cross-language link-session state-machine vectors
// (W-N18 A08e): ../../../apps/RelayiumKit/Tests/Fixtures/link-session-vectors.json,
// generated by web/scripts/gen-link-session-vectors.mjs from the Web authority
// and gated byte-for-byte by web/scripts/check-wire-vectors.mjs.
//
// Each scenario drives a REAL Session: two sessions are paired and opened over
// the loopback harness, then the subject is driven directly while the other
// session's own link codecs (its FileSender / TextSender, i.e. the peer's real
// keys) seal every frame the scripted peer sends. Timer steps advance the
// injected fake clock and Tick. Nothing here re-implements a lane rule: the
// state and the tokens compared are what the subject's tables and runtime
// produced.

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"testing"
	"time"

	"github.com/relayium/relayium/internal/linkwire"
)

const linkSessionVectorsPath = "../../../apps/RelayiumKit/Tests/Fixtures/link-session-vectors.json"

const vecMe = "go"

type vecExpect struct {
	Emit  []string `json:"emit"`
	State string   `json:"state"`
}

type vecStep struct {
	Do     string    `json:"do"`
	Auto   []string  `json:"auto"`
	Expect vecExpect `json:"expect"`
}

type vecDivergence struct {
	Consumer  string    `json:"consumer"`
	Step      int       `json:"step"`
	Expect    vecExpect `json:"expect"`
	StopAfter bool      `json:"stopAfter"`
	FollowUp  string    `json:"followUp"`
}

type vecScenario struct {
	Name        string            `json:"name"`
	Role        string            `json:"role"`
	Consumers   []string          `json:"consumers"`
	Skip        map[string]string `json:"skip"`
	Steps       []vecStep         `json:"steps"`
	Divergences []vecDivergence   `json:"divergences"`
}

type vecCliStep struct {
	Do     string          `json:"do"`
	View   map[string]bool `json:"view"`
	Signal json.RawMessage `json:"signal"`
	Expect vecExpect       `json:"expect"`
}

type vecCliScenario struct {
	Name      string       `json:"name"`
	Cmd       string       `json:"cmd"`
	Consumers []string     `json:"consumers"`
	Steps     []vecCliStep `json:"steps"`
}

type vecFixture struct {
	Format    string           `json:"format"`
	Authority string           `json:"authority"`
	Bounds    map[string]int64 `json:"bounds"`
	File      []vecScenario    `json:"file"`
	Text      []vecScenario    `json:"text"`
	Cli       []vecCliScenario `json:"cli"`
	AppPeers  struct {
		KindLatchesCli struct {
			Consumers []string `json:"consumers"`
			Cases     []struct {
				Signal json.RawMessage `json:"signal"`
				Cli    bool            `json:"cli"`
			} `json:"cases"`
		} `json:"kindLatchesCli"`
	} `json:"appPeers"`
}

func loadLinkSessionVectors(t *testing.T) *vecFixture {
	t.Helper()
	raw, err := os.ReadFile(linkSessionVectorsPath)
	if err != nil {
		t.Fatalf("read %s: %v", linkSessionVectorsPath, err)
	}
	var v vecFixture
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse %s: %v", linkSessionVectorsPath, err)
	}
	if v.Format != "relayium-link-session-vectors/1" || v.Authority != "web" {
		t.Fatalf("unexpected fixture format %q / authority %q", v.Format, v.Authority)
	}
	return &v
}

func vecHas(list []string, s string) bool {
	for _, x := range list {
		if x == s {
			return true
		}
	}
	return false
}

type vecPlanned struct {
	index     int
	do        string
	expect    vecExpect
	stopAfter bool
}

// planFor is the fixture's stepSemantics for this consumer: auto steps merge
// onto the previous one, then divergences replace (and are asserted).
func planFor(t *testing.T, s vecScenario) []vecPlanned {
	t.Helper()
	var out []vecPlanned
	for i, st := range s.Steps {
		if vecHas(st.Auto, vecMe) {
			if len(out) == 0 {
				t.Fatalf("%s: step %d is auto for go with no previous step", s.Name, i)
			}
			p := &out[len(out)-1]
			p.expect = vecExpect{Emit: append(append([]string{}, p.expect.Emit...), st.Expect.Emit...), State: st.Expect.State}
			continue
		}
		out = append(out, vecPlanned{index: i, do: st.Do, expect: vecExpect{Emit: append([]string{}, st.Expect.Emit...), State: st.Expect.State}})
	}
	for _, d := range s.Divergences {
		if d.Consumer != vecMe {
			continue
		}
		found := false
		for i := range out {
			if out[i].index == d.Step {
				out[i].expect = vecExpect{Emit: append([]string{}, d.Expect.Emit...), State: d.Expect.State}
				out[i].stopAfter = d.StopAfter
				found = true
			}
		}
		if !found {
			t.Fatalf("%s: divergence names step %d, which go does not perform", s.Name, d.Step)
		}
	}
	return out
}

// ---------------------------------------------------------------- tokens

func fileToken(b []byte) (string, bool) {
	if len(b) == 1 {
		switch b[0] {
		case linkwire.CtrlAccept:
			return "ACCEPT", true
		case linkwire.CtrlReject:
			return "REJECT", true
		case linkwire.CtrlComplete:
			return "COMPLETE", true
		case linkwire.CtrlBusy:
			return "BUSY", true
		case linkwire.CtrlBatchAbort:
			return "BATCH_ABORT", true
		}
		return fmt.Sprintf("CTRL(%#02x)", b[0]), true
	}
	switch b[0] {
	case linkwire.KindBatchPart, linkwire.KindChunkPart:
		return "", false
	case linkwire.KindBatchEnc:
		return "MANIFEST", true
	case linkwire.KindChunk:
		return "CHUNK", true
	case linkwire.KindDoneEnc:
		return "DONE", true
	case linkwire.KindAck:
		return "ACK", true
	}
	return fmt.Sprintf("KIND(%d)", b[0]), true
}

func textToken(b []byte) string {
	if len(b) == 1 {
		switch b[0] {
		case linkwire.CtrlTextRequest:
			return "REQUEST"
		case linkwire.CtrlAccept:
			return "ACCEPT"
		case linkwire.CtrlReject:
			return "REJECT"
		case linkwire.CtrlTextEnd:
			return "END"
		}
		return fmt.Sprintf("CTRL(%#02x)", b[0])
	}
	if b[0] == linkwire.KindText {
		return "MESSAGE"
	}
	return fmt.Sprintf("KIND(%d)", b[0])
}

func laneTokens(effs []Effect, text bool) []string {
	out := []string{}
	for _, e := range effs {
		switch {
		case !text && e.Kind == EffSendFile:
			if tok, ok := fileToken(e.Bytes); ok {
				out = append(out, tok)
			}
		case text && e.Kind == EffSendText:
			out = append(out, textToken(e.Bytes))
		}
	}
	return out
}

// ---------------------------------------------------------------- bounds

func vecBound(t *testing.T, v *vecFixture, name string) time.Duration {
	t.Helper()
	ms, ok := v.Bounds[name]
	if !ok {
		t.Fatalf("fixture has no bound %q", name)
	}
	return time.Duration(ms) * time.Millisecond
}

func TestLinkSessionVectorsBounds(t *testing.T) {
	v := loadLinkSessionVectors(t)
	mine := map[string]time.Duration{
		"fileConsent":   FileConsent,
		"fileDrain":     FileDrainWait,
		"textConsent":   TextConsent,
		"textEndAck":    TextEndAckWait,
		"helloInterval": HelloInterval,
	}
	for k, d := range mine {
		if got := vecBound(t, v, k); got != d {
			t.Errorf("bound %s: fixture %v, linksession %v", k, got, d)
		}
	}
	// fileReplay has no Go counterpart: the CLI replays a yielded batch at once
	// (divergence A08e-D3, asserted by file.glare.responder-yields).
	for k := range v.Bounds {
		if _, ok := mine[k]; !ok && k != "fileReplay" {
			t.Errorf("fixture bound %q is not mapped by the Go consumer", k)
		}
	}
}

func TestLinkSessionVectorsCoverage(t *testing.T) {
	v := loadLinkSessionVectors(t)
	for _, s := range append(append([]vecScenario{}, v.File...), v.Text...) {
		listed, skipped := vecHas(s.Consumers, vecMe), s.Skip[vecMe] != ""
		if listed == skipped {
			t.Errorf("%s: go must be listed or skipped with a reason (listed=%v skipped=%v)", s.Name, listed, skipped)
		}
		for _, d := range s.Divergences {
			if d.FollowUp == "" {
				t.Errorf("%s: divergence for %s has no follow-up", s.Name, d.Consumer)
			}
		}
	}
}

// ---------------------------------------------------------------- lane harness

type vecLane struct {
	t       *testing.T
	l       *loop
	subject *end
	peer    *end
	// the scripted peer's in-progress file (for content / done / mismatch)
	peerBody []byte
	peerSent bool
}

func newVecLane(t *testing.T, role string) *vecLane {
	t.Helper()
	l := openLoop(t, CmdPair, CmdPair)
	subject, peer := l.a, l.b // "a" < "b": a is the initiator
	if role == "responder" {
		subject, peer = l.b, l.a
	} else if role != "initiator" {
		t.Fatalf("unknown role %q", role)
	}
	// The vectors pin the interactive prompt for both kinds. `pair` auto-accepts
	// text today (AuthzFor); that is a command policy layered above the lane,
	// and the lane semantics under a prompt are what every consumer shares.
	subject.s.authz = Authz{Files: PolicyPrompt, Text: PolicyPrompt}
	return &vecLane{t: t, l: l, subject: subject, peer: peer}
}

func (v *vecLane) must(effs []Effect, err error) []Effect {
	v.t.Helper()
	_ = err // refusals are part of the behaviour under test; the effects are what is compared
	return effs
}

func (v *vecLane) file(raw []byte) []Effect {
	return v.must(v.subject.s.FileFrame(v.subject.s.Epoch(), raw))
}

func (v *vecLane) text(raw []byte) []Effect {
	return v.must(v.subject.s.TextFrame(v.subject.s.Epoch(), raw))
}

var vecPeerFile = linkwire.FileMeta{Name: "hello.txt", Size: 5}

func (v *vecLane) peerManifest(deliver bool) []Effect {
	v.t.Helper()
	frames, err := v.peer.s.lk.fileTx.BatchFrames([]linkwire.FileMeta{vecPeerFile}, DefaultMaxFrameBytes)
	if err != nil {
		v.t.Fatal(err)
	}
	v.peerBody, v.peerSent = []byte("hello"), false
	var out []Effect
	if deliver {
		for _, f := range frames {
			out = append(out, v.file(f)...)
		}
	}
	return out
}

func (v *vecLane) peerContent() []Effect {
	v.t.Helper()
	if v.peerBody == nil || v.peerSent {
		v.t.Fatal("scripted peer: no content left in the announced batch")
	}
	frames, err := v.peer.s.lk.fileTx.ChunkFrames(v.peerBody, DefaultMaxFrameBytes)
	if err != nil {
		v.t.Fatal(err)
	}
	v.peerSent = true
	var out []Effect
	for _, f := range frames {
		out = append(out, v.file(f)...)
	}
	return out
}

func (v *vecLane) peerDone(mismatch bool) []Effect {
	v.t.Helper()
	tx := v.peer.s.lk.fileTx
	if !mismatch {
		f, err := tx.DoneFrame()
		if err != nil {
			v.t.Fatal(err)
		}
		return v.file(f)
	}
	// A DONE at the right sequence whose digest is for different bytes: a copy
	// of the peer's sender re-hashes "hellp" and seals the DONE, then the real
	// sender seals (and drops) its own so its sequence stays where the wire is.
	twin := *tx
	twin.AbortBatch()
	if err := twin.SkipChunk([]byte("hellp")); err != nil {
		v.t.Fatal(err)
	}
	wrong, err := twin.DoneFrame()
	if err != nil {
		v.t.Fatal(err)
	}
	if _, err := tx.DoneFrame(); err != nil {
		v.t.Fatal(err)
	}
	return v.file(wrong)
}

func (v *vecLane) tick(d time.Duration) []Effect {
	v.l.clk.Advance(d)
	return v.must(v.subject.s.Tick())
}

func runGoFileScenario(t *testing.T, fx *vecFixture, sc vecScenario) {
	v := newVecLane(t, sc.Role)
	s := v.subject.s
	for _, p := range planFor(t, sc) {
		var effs []Effect
		switch op := p.do; {
		case op == "local:offer":
			effs = v.must(s.OfferFiles([]linkwire.FileMeta{{Name: "out.txt", Size: 5}}))
		case op == "local:send-all":
			effs = append(v.must(s.SendChunk([]byte("hello"))), v.must(s.EndFile())...)
		case op == "local:accept":
			effs = v.must(s.AcceptFiles(s.filePrompt))
		case op == "local:reject":
			effs = v.must(s.RejectFiles(s.filePrompt))
		case op == "local:cancel-in":
			effs = v.must(s.CancelIncoming())
		case op == "local:cancel-out":
			effs = v.must(s.CancelOutgoing())
		case op == "local:durable":
			effs = v.must(s.FileDurable(s.Epoch(), s.fin.received))
		case op == "local:commit":
			// COMPLETE follows verification and durability inside the session;
			// there is no separate export call, so this step is `auto` for go.
			t.Fatalf("%s: local:commit must be auto for go", sc.Name)
		case op == "peer:manifest":
			effs = v.peerManifest(true)
		case op == "peer:content":
			effs = v.peerContent()
		case op == "peer:done":
			effs = v.peerDone(false)
		case op == "peer:done-mismatch":
			effs = v.peerDone(true)
		case op == "peer:content-unannounced":
			v.peerManifest(false)
			effs = v.peerContent()
		case op == "peer:ACCEPT":
			effs = v.file([]byte{linkwire.CtrlAccept})
		case op == "peer:REJECT":
			effs = v.file([]byte{linkwire.CtrlReject})
		case op == "peer:BUSY":
			effs = v.file([]byte{linkwire.CtrlBusy})
		case op == "peer:BATCH_ABORT":
			effs = v.file([]byte{linkwire.CtrlBatchAbort})
		case op == "peer:COMPLETE":
			effs = v.file([]byte{linkwire.CtrlComplete})
		case len(op) > 6 && op[:6] == "timer:":
			effs = v.tick(vecBound(t, fx, op[6:]))
		default:
			t.Fatalf("%s: the Go file consumer cannot map step %q", sc.Name, op)
		}
		_, _, file, _ := s.States()
		got := vecExpect{Emit: laneTokens(effs, false), State: file}
		if !reflect.DeepEqual(got, p.expect) {
			t.Fatalf("%s step %d (%s): got %+v, want %+v (effects: %s)", sc.Name, p.index, p.do, got, p.expect, kinds(effs))
		}
		if p.stopAfter {
			return
		}
	}
}

func runGoTextScenario(t *testing.T, fx *vecFixture, sc vecScenario) {
	v := newVecLane(t, sc.Role)
	s := v.subject.s
	for _, p := range planFor(t, sc) {
		var effs []Effect
		switch op := p.do; {
		case op == "local:request":
			effs = v.must(s.RequestText())
		case op == "local:accept":
			effs = v.must(s.AcceptText(s.textPrompt))
		case op == "local:reject":
			effs = v.must(s.RejectText(s.textPrompt))
		case op == "local:end":
			effs = v.must(s.EndText())
		case op == "local:send":
			effs = v.must(s.SendText([]byte("hi there"), 0))
		case op == "peer:REQUEST":
			effs = v.text([]byte{linkwire.CtrlTextRequest})
		case op == "peer:ACCEPT":
			effs = v.text([]byte{linkwire.CtrlAccept})
		case op == "peer:REJECT":
			effs = v.text([]byte{linkwire.CtrlReject})
		case op == "peer:END":
			effs = v.text([]byte{linkwire.CtrlTextEnd})
		case op == "peer:message":
			f, err := v.peer.s.lk.textTx.Seal([]byte("from peer"))
			if err != nil {
				t.Fatal(err)
			}
			effs = v.text(f)
		case op == "peer:unknown":
			effs = v.text([]byte{0x0d, 0x00})
		case op == "peer:short9":
			effs = v.text([]byte{0x09, 0x00, 0x00})
		case len(op) > 6 && op[:6] == "timer:":
			effs = v.tick(vecBound(t, fx, op[6:]))
		default:
			t.Fatalf("%s: the Go text consumer cannot map step %q", sc.Name, op)
		}
		_, _, _, text := s.States()
		got := vecExpect{Emit: laneTokens(effs, true), State: text}
		if !reflect.DeepEqual(got, p.expect) {
			t.Fatalf("%s step %d (%s): got %+v, want %+v (effects: %s)", sc.Name, p.index, p.do, got, p.expect, kinds(effs))
		}
		if p.stopAfter {
			return
		}
	}
}

func TestLinkSessionVectorsFileLane(t *testing.T) {
	fx := loadLinkSessionVectors(t)
	n := 0
	for _, sc := range fx.File {
		if !vecHas(sc.Consumers, vecMe) {
			continue
		}
		n++
		t.Run(sc.Name, func(t *testing.T) { runGoFileScenario(t, fx, sc) })
	}
	if n == 0 {
		t.Fatal("no file-lane scenario names go: the suite would assert nothing")
	}
}

func TestLinkSessionVectorsTextLane(t *testing.T) {
	fx := loadLinkSessionVectors(t)
	n := 0
	for _, sc := range fx.Text {
		if !vecHas(sc.Consumers, vecMe) {
			continue
		}
		n++
		t.Run(sc.Name, func(t *testing.T) { runGoTextScenario(t, fx, sc) })
	}
	if n == 0 {
		t.Fatal("no text-lane scenario names go: the suite would assert nothing")
	}
}

// ---------------------------------------------------------------- CLI discovery

// cliTokens keeps the emissions the discovery machine owns: the link/1 hello,
// a kind frame (only ever the upgrade notice) and the legacy hand-off. Link
// establishment traffic (link-request, offers) belongs to the link machine and
// is not part of these vectors.
func cliTokens(effs []Effect) []string {
	out := []string{}
	for _, e := range effs {
		switch e.Kind {
		case EffSendSignal:
			var m map[string]json.RawMessage
			if json.Unmarshal(e.Bytes, &m) != nil {
				continue
			}
			if k, ok := m["kind"]; ok {
				var kind string
				_ = json.Unmarshal(k, &kind)
				out = append(out, "KIND:"+kind)
			} else if _, ok := m["caps"]; ok {
				out = append(out, "HELLO")
			}
		case EffBeginLegacy:
			out = append(out, "LEGACY")
		}
	}
	return out
}

func vecCmd(t *testing.T, name string) Cmd {
	switch name {
	case "pair":
		return CmdPair
	case "send":
		return CmdSend
	case "receive":
		return CmdReceive
	case "text":
		return CmdText
	}
	t.Fatalf("unknown cmd %q", name)
	return 0
}

func TestLinkSessionVectorsCliDiscovery(t *testing.T) {
	fx := loadLinkSessionVectors(t)
	if len(fx.Cli) == 0 {
		t.Fatal("no cli scenarios")
	}
	for _, sc := range fx.Cli {
		if !vecHas(sc.Consumers, vecMe) {
			t.Fatalf("%s: cli scenarios are Go's own machine and must name go", sc.Name)
		}
		t.Run(sc.Name, func(t *testing.T) {
			clk := newClock()
			s, err := NewSession(Config{Cmd: vecCmd(t, sc.Cmd), Clock: clk, Rand: newRand(9)})
			if err != nil {
				t.Fatal(err)
			}
			for i, st := range sc.Steps {
				var effs []Effect
				switch st.Do {
				case "room":
					effs, _ = s.Room(s.Epoch(), RoomView{SelfID: "b", PeerID: "a",
						ServerHints: st.View["serverHints"], PeerHinted: st.View["peerHinted"]})
				case "signal":
					effs, _ = s.Signal(s.Epoch(), "a", st.Signal)
				case "timer:helloInterval":
					clk.Advance(vecBound(t, fx, "helloInterval"))
					effs, _ = s.Tick()
				default:
					t.Fatalf("%s: the Go cli consumer cannot map step %q", sc.Name, st.Do)
				}
				disc, _, _, _ := s.States()
				got := vecExpect{Emit: cliTokens(effs), State: disc}
				if !reflect.DeepEqual(got, st.Expect) {
					t.Fatalf("%s step %d (%s): got %+v, want %+v (effects: %s)", sc.Name, i, st.Do, got, st.Expect, kinds(effs))
				}
			}
		})
	}
}

func TestLinkSessionVectorsKindLatchesCli(t *testing.T) {
	fx := loadLinkSessionVectors(t)
	m := fx.AppPeers.KindLatchesCli
	if !vecHas(m.Consumers, vecMe) || len(m.Cases) == 0 {
		t.Fatal("app.kind-latches-cli does not name go, or has no cases")
	}
	for _, c := range m.Cases {
		ev := ClassifySignal(c.Signal)
		cli := ev == DSigLegacyCommit || ev == DSigLegacyOther
		if cli != c.Cli {
			t.Errorf("%s: classified as kind frame = %v, fixture says %v", c.Signal, cli, c.Cli)
		}
	}
}
