import XCTest
@testable import RelayiumKit

final class KeyAgreementTests: XCTestCase {
    func testDeriveSessionMatchesVectors() throws {
        let v = try Vectors.load()
        let alice = KeyPair(publicKey: v.hex("alice.pub"), secretKey: v.hex("alice.sec"))
        let bobPub = v.hex("bob.pub")
        let keys = try deriveSession(role: .initiator, self: alice, peerPublic: bobPub)
        XCTAssertEqual(keys.send, v.hex("session.aliceSend"))
        XCTAssertEqual(keys.recv, v.hex("session.aliceRecv"))
    }

    // The message stream's keys are domain-separated from the file stream's. The
    // vectors are generated by the web implementation, so this is a cross-check
    // between the two ports rather than a restatement of this one.
    func testDeriveTextKeysMatchVectors() throws {
        let v = try Vectors.load()
        XCTAssertEqual(TEXT_KEY_DOMAIN, Array("relayium-text-v1\u{0}".utf8))
        XCTAssertEqual(deriveTextKey(sessionKey: v.hex("session.aliceSend")), v.hex("textKeys.aliceTextSend"))
        XCTAssertEqual(deriveTextKey(sessionKey: v.hex("session.aliceRecv")), v.hex("textKeys.aliceTextRecv"))
    }

    // crypto_kx hands the peers mirrored secrets, so hashing each locally lines the
    // two directions up with no extra round trip -- which is why this derivation
    // does NOT sort its input the way deriveResumeAuth must.
    func testTextKeysMirrorAcrossThePeers() throws {
        let v = try Vectors.load()
        let aliceSend = deriveTextKey(sessionKey: v.hex("session.aliceSend"))
        let bobRecv = deriveTextKey(sessionKey: v.hex("session.bobRecv"))
        XCTAssertEqual(aliceSend, bobRecv)
        XCTAssertEqual(
            deriveTextKey(sessionKey: v.hex("session.bobSend")),
            deriveTextKey(sessionKey: v.hex("session.aliceRecv"))
        )
        // And the two directions are distinct, so a frame cannot be reflected back
        // at its sender and opened.
        XCTAssertNotEqual(aliceSend, deriveTextKey(sessionKey: v.hex("session.aliceRecv")))
    }

    // Domain separation has to actually participate: without the prefix this would
    // be a bare hash of a session secret, replayable into any other context that
    // hashes the same secret.
    func testTextKeyIsDomainSeparated() throws {
        let v = try Vectors.load()
        let secret = v.hex("session.aliceSend")
        XCTAssertNotEqual(deriveTextKey(sessionKey: secret), genericHash(secret, outputLength: 32))
        XCTAssertNotEqual(deriveTextKey(sessionKey: secret), secret)
    }

    func testDeriveSessionRejectsShortPeerKey() throws {
        let alice = generateKeyPair()
        XCTAssertThrowsError(
            try deriveSession(role: .initiator, self: alice, peerPublic: [1,2,3,4])
        ) { error in
            XCTAssertEqual(error as? CryptoError, CryptoError.keyAgreementFailed)
        }
    }

    func testDeriveSessionThrowsOnInvalidPeerKey() throws {
        let v = try Vectors.load()
        let alice = KeyPair(publicKey: v.hex("alice.pub"), secretKey: v.hex("alice.sec"))
        let allZeroPeerPublic = [UInt8](repeating: 0, count: 32)
        XCTAssertThrowsError(
            try deriveSession(role: .initiator, self: alice, peerPublic: allZeroPeerPublic)
        ) { error in
            XCTAssertEqual(error as? CryptoError, CryptoError.keyAgreementFailed)
        }
    }
}
