import XCTest
@testable import RelayiumKit
final class RealtimeFrameTests: XCTestCase {
    func testConstants() {
        XCTAssertEqual(CHUNK_SIZE, 192*1024); XCTAssertEqual(CHUNK_OVERHEAD, 21)
        XCTAssertEqual(FLOW_WINDOW, 8<<20); XCTAssertEqual(FLOW_ACK_INTERVAL, 512*1024)
    }
    func testFrameLayout() {
        let f = realtimeFrame(kind: 1, seq: 0x01020304, payload: [0xaa,0xbb])
        XCTAssertEqual(f, [1, 0x01,0x02,0x03,0x04, 0xaa,0xbb])
    }
    func testAckMatchesVector() throws {
        let v = try Vectors.load("realtime-wire-vectors")
        XCTAssertEqual(ackFrame(1_048_576), v.hex("ackHex"))
        XCTAssertEqual(parseAck(v.hex("ackHex")), 1_048_576)
        XCTAssertNil(parseAck([1,2,3]))
    }
    func testControl() {
        XCTAssertEqual(parseControl([0xfe]), .accept)
        XCTAssertEqual(parseControl([0xfd]), .complete)
        XCTAssertNil(parseControl([0xfe, 0x00]))   // must be exactly 1 byte
        XCTAssertNil(parseControl([0x01]))
    }
}

// ── message frames (kind 9) ──────────────────────────────────────────────────
extension RealtimeFrameTests {
    func testTextKindIsNineAndDistinct() {
        XCTAssertEqual(RealtimeKind.text, 9)
        let fileKinds: [UInt8] = [
            RealtimeKind.chunk, RealtimeKind.doneLegacy, RealtimeKind.batchLegacy,
            RealtimeKind.resumeStart, RealtimeKind.resumeReq, RealtimeKind.ack,
            RealtimeKind.batchEnc, RealtimeKind.doneEnc,
        ]
        XCTAssertFalse(fileKinds.contains(RealtimeKind.text))
        XCTAssertEqual(TEXT_MAX_BYTES, 64 * 1024)
    }

    // Vectors generated by the web implementation: a byte/character confusion in
    // this port fails here rather than in the field.
    func testTextFramesFromVectorsOpenToExactUTF8() throws {
        let v = try Vectors.load("realtime-wire-vectors")
        let key = v.hex("text.keyHex")
        let frames = v.json["text"] as! [String: Any]
        let cases = frames["frames"] as! [[String: Any]]
        XCTAssertFalse(cases.isEmpty)
        for c in cases {
            let seq = c["seq"] as! Int
            let want = c["body"] as! String
            let frame = (c["frameHex"] as! String).hexBytes

            XCTAssertEqual(frame[0], RealtimeKind.text)
            let onWireSeq = (UInt32(frame[1]) << 24) | (UInt32(frame[2]) << 16)
                | (UInt32(frame[3]) << 8) | UInt32(frame[4])
            XCTAssertEqual(Int(onWireSeq), seq)

            guard let plain = open(key: key, seq: UInt64(seq), ciphertext: Array(frame[5...])) else {
                return XCTFail("frame at seq \(seq) failed to open")
            }
            // Strict UTF-8: String(bytes:encoding:) returns nil rather than
            // substituting U+FFFD, which is the behaviour the wire requires.
            guard let got = String(bytes: plain, encoding: .utf8) else {
                return XCTFail("frame at seq \(seq) did not decode as UTF-8")
            }
            XCTAssertEqual(got, want)
            XCTAssertEqual(plain, Array(want.utf8), "bytes must match, not just the string")
        }
    }

    func testTextFrameRejectsInvalidUTF8() {
        // A lone continuation byte is not valid UTF-8 and must not become U+FFFD.
        XCTAssertNil(String(bytes: [0x80] as [UInt8], encoding: .utf8))
    }

    // The accept/reject bytes the message session uses for its consent handshake
    // are the file protocol's existing control bytes, unchanged, and structurally
    // disjoint from a kind-9 frame (1 byte vs at least 21).
    func testMessageConsentReusesTheControlBytes() throws {
        let v = try Vectors.load("realtime-wire-vectors")
        let control = v.json["controlHex"] as! [String: Any]
        XCTAssertEqual((control["accept"] as! String).hexBytes, [RealtimeControl.accept.rawValue])
        XCTAssertEqual((control["reject"] as! String).hexBytes, [RealtimeControl.reject.rawValue])
        XCTAssertEqual(parseControl([RealtimeControl.accept.rawValue]), .accept)
        XCTAssertEqual(parseControl([RealtimeControl.reject.rawValue]), .reject)
        // A message frame is never a control frame.
        let frames = (v.json["text"] as! [String: Any])["frames"] as! [[String: Any]]
        let first = ((frames[0]["frameHex"] as! String)).hexBytes
        XCTAssertGreaterThanOrEqual(first.count, 21)
        XCTAssertNil(parseControl(first))
    }
}
