package com.relayium.protocol.inbox

import com.relayium.protocol.Bytes
import kotlin.test.assertFailsWith
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.bouncycastle.math.ec.rfc7748.X25519
import org.junit.Test

/**
 * `x25519-sealedbox-v1` against bytes libsodium produced, and each composed step
 * against a published known-answer test.
 *
 * The vectors below were generated by the installed `libsodium-wrappers` and
 * transcribed once; they are not derived from this implementation, which is the
 * whole point — a codec checked against its own output agrees with itself and
 * with nobody. The private halves are generated TEST material: they wrap a
 * fixture content key and have never been a device identity.
 *
 * The negative controls matter as much as the positives. A sealed box that
 * cannot be forged is worth nothing if the opener accepts a tampered one, and a
 * low-order target key would make every "wrap" recoverable by anybody while the
 * happy path still passed.
 */
class InboxSealedBoxTest {

    // ── libsodium's answers ─────────────────────────────────────────────────

    private val recipientPublic = Bytes.unhex("165e7e1571a344bb26d1bdd9c423b92baad7ed89463802dda090315d18be0f3d")
    private val recipientPrivate = Bytes.unhex("998e5c508da88cab41dc159610327359b206cdc95a5b3f9ddec2cba4575cf81c")
    private val ephemeralPublic = Bytes.unhex("fa280f26a36476d4fa59f462e7623bf2a64999e1ca041ce032f80db985f1384b")
    private val ephemeralPrivate = Bytes.unhex("7e220ab8d053530bd710db03b8f58f89764ee7e8131f79f802b3b853814a82a1")
    private val contentKey = Bytes.unhex("286f07531931e5c3a9a2f8dd7f942f100877cb09c0b4d79a325da2b6e4ac7888")
    private val beforeNm = Bytes.unhex("4cce0c11256bdfec49ca55ad02767daaa2c70c68805f3b1446ad89f830fb2fb2")
    private val nonce = Bytes.unhex("7755555bb3ce3aa4971f6bb423bc2c948149591b834d32f7")

    /** `crypto_box_easy` under the fixed ephemeral key above, which libsodium
     *  itself confirmed is what `crypto_box_seal` produces for it. */
    private val deterministicSeal = Bytes.unhex(
        "fa280f26a36476d4fa59f462e7623bf2a64999e1ca041ce032f80db985f1384b" +
            "44baf6370b53782cf1172df31f36cddb" +
            "ad20d5d45104b750b010ffe709ab1658f45ca2dcf791d54119a11794c396d379",
    )

    /** A seal whose ephemeral key libsodium chose, so the open path is proved
     *  against a box this implementation had no part in constructing. */
    private val sodiumSeal = Bytes.unhex(
        "bc3c942252cbd5716b0137f467642a4aba6a81325bcd5f506edcbd6b93abf96b" +
            "385044f5274c9f6d4aa1c09858ce85e8" +
            "75cb721a48bf2868830bb129c2cb8a482c802625abd8b380b0b1da5278107dbc",
    )

    /** Low-order points, each confirmed refused by libsodium's own
     *  `crypto_scalarmult` when the vectors were generated. */
    private val lowOrderPoints = listOf(
        "0000000000000000000000000000000000000000000000000000000000000000",
        "0100000000000000000000000000000000000000000000000000000000000000",
        "e0eb7a7c3b41b8ae1656e3faf19fc46ada098deb9c32b1fd866205165f49b800",
    ).map(Bytes::unhex)

    private val keyPair get() = InboxDeviceKeyPair(recipientPublic, recipientPrivate)
    private val algorithm = InboxProtocol.KEY_ALGORITHM

    // ── each step, then the whole box ───────────────────────────────────────

    @Test
    fun `beforenm is HSalsa20 of the shared point, from either side`() {
        assertArrayEquals(beforeNm, InboxKeyMaterial.beforeNm(ephemeralPrivate, recipientPublic))
        // The same key from the other direction is what makes the box openable
        // at all; a one-sided derivation would still pass the seal test.
        assertArrayEquals(beforeNm, InboxKeyMaterial.beforeNm(recipientPrivate, ephemeralPublic))
    }

    @Test
    fun `the nonce is BLAKE2b-24 of ephemeral then recipient, in that order`() {
        assertArrayEquals(nonce, InboxKeyMaterial.sealNonce(ephemeralPublic, recipientPublic))
        assertFalse(
            "the operand order is part of the contract",
            nonce.contentEquals(InboxKeyMaterial.sealNonce(recipientPublic, ephemeralPublic)),
        )
    }

    @Test
    fun `the sealed box is byte-identical to libsodium's`() {
        val sealed = InboxKeyMaterial.sealRaw(recipientPublic, contentKey, ephemeralPrivate)
        assertArrayEquals(deterministicSeal, sealed)
        assertEquals(InboxProtocol.SEALED_BOX_BYTES, sealed.size)
        // The layout, asserted separately from the bytes: ephemeral key, then
        // the tag, then the ciphertext.
        assertArrayEquals(ephemeralPublic, sealed.copyOf(32))
    }

    @Test
    fun `libsodium's own seals open to the exact 32-byte content key`() {
        for (sealed in listOf(deterministicSeal, sodiumSeal)) {
            val opened = InboxKeyMaterial.unsealContentKey(algorithm, InboxKeyMaterial.encode(sealed), keyPair)
            assertArrayEquals(contentKey, opened)
            assertEquals(InboxProtocol.CONTENT_KEY_BYTES, opened.size)
        }
    }

    @Test
    fun `this implementation round-trips its own freshly generated identity`() {
        val pair = InboxKeyMaterial.generateKeyPair()
        val announced = InboxKeyMaterial.encode(pair.publicKey)
        assertArrayEquals(pair.publicKey, InboxKeyMaterial.validatePublicKey(algorithm, announced))
        val wrapped = InboxKeyMaterial.sealContentKey(algorithm, announced, contentKey)
        assertArrayEquals(contentKey, InboxKeyMaterial.unsealContentKey(algorithm, wrapped, pair))
        // A fresh ephemeral key per seal: two wraps of one content key to one
        // device must never be the same bytes, or the nonce repeated.
        assertNotEquals(wrapped, InboxKeyMaterial.sealContentKey(algorithm, announced, contentKey))
    }

    // ── negative controls ───────────────────────────────────────────────────

    @Test
    fun `a tamper anywhere in the box is refused`() {
        // One case per region: the ephemeral key (which re-keys the whole box),
        // the tag, and the ciphertext.
        for (index in listOf(0, 31, 32, 47, 48, 79)) {
            val tampered = sodiumSeal.copyOf().also { it[index] = (it[index].toInt() xor 1).toByte() }
            val thrown = assertFailsWith<InboxKeyException>("byte $index") {
                InboxKeyMaterial.unsealContentKey(algorithm, InboxKeyMaterial.encode(tampered), keyPair)
            }
            assertEquals(InboxKeyReason.UNSEAL, thrown.reason)
        }
    }

    @Test
    fun `a box sealed to somebody else is refused, opaquely`() {
        val stranger = InboxKeyMaterial.generateKeyPair()
        assertEquals(
            InboxKeyReason.UNSEAL,
            assertFailsWith<InboxKeyException> {
                InboxKeyMaterial.unsealContentKey(algorithm, InboxKeyMaterial.encode(sodiumSeal), stranger)
            }.reason,
        )
        // A pair whose halves are two different identities fails the same way,
        // and as a TYPED refusal rather than as whatever a primitive raises.
        val mixed = InboxDeviceKeyPair(stranger.publicKey, recipientPrivate)
        assertEquals(
            InboxKeyReason.UNSEAL,
            assertFailsWith<InboxKeyException> {
                InboxKeyMaterial.unsealContentKey(algorithm, InboxKeyMaterial.encode(sodiumSeal), mixed)
            }.reason,
        )
    }

    @Test
    fun `a low-order target key is refused before anything is wrapped to it`() {
        for (point in lowOrderPoints) {
            assertTrue(InboxKeyMaterial.isLowOrder(point))
            val encoded = InboxKeyMaterial.encode(point)
            assertEquals(
                InboxKeyReason.UNUSABLE_PUBLIC_KEY,
                assertFailsWith<InboxKeyException> {
                    InboxKeyMaterial.validatePublicKey(algorithm, encoded)
                }.reason,
            )
            assertEquals(
                InboxKeyReason.UNUSABLE_PUBLIC_KEY,
                assertFailsWith<InboxKeyException> {
                    InboxKeyMaterial.sealContentKey(algorithm, encoded, contentKey)
                }.reason,
            )
        }
        assertFalse(InboxKeyMaterial.isLowOrder(recipientPublic))
        // Any wrong length is unusable too, rather than reaching a primitive.
        assertTrue(InboxKeyMaterial.isLowOrder(ByteArray(31)))
    }

    @Test
    fun `only the exact algorithm token is honoured`() {
        for (token in listOf("", "x25519-sealedbox-v2", "X25519-SEALEDBOX-V1", "rsa-oaep")) {
            assertEquals(
                InboxKeyReason.UNSUPPORTED_ALGORITHM,
                assertFailsWith<InboxKeyException> {
                    InboxKeyMaterial.validatePublicKey(token, InboxKeyMaterial.encode(recipientPublic))
                }.reason,
            )
            assertEquals(
                InboxKeyReason.UNSUPPORTED_ALGORITHM,
                assertFailsWith<InboxKeyException> {
                    InboxKeyMaterial.unsealContentKey(token, InboxKeyMaterial.encode(sodiumSeal), keyPair)
                }.reason,
            )
        }
    }

    @Test
    fun `key material has exactly one spelling`() {
        val encoded = InboxKeyMaterial.encode(recipientPublic)
        assertEquals(43, encoded.length)
        assertEquals(107, InboxKeyMaterial.encode(sodiumSeal).length)
        assertArrayEquals(recipientPublic, InboxKeyMaterial.decode(encoded, 32))

        val alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
        // The last character of a 32-byte key carries 4 data bits and 2 spare
        // ones. Flipping a spare bit decodes to the SAME key, which is exactly
        // the second spelling an identity comparison must never see.
        val spare = encoded.dropLast(1) + alphabet[alphabet.indexOf(encoded.last()) xor 1]
        assertNotEquals(encoded, spare)

        val rejected = listOf(
            spare,
            "$encoded=", // padded
            encoded.dropLast(1), // short
            encoded + "A", // long
            "+" + encoded.substring(1), // standard alphabet
            " $encoded", // whitespace
            "",
            "A".repeat(1 shl 20), // refused on length, before any scan or decode
        )
        for (text in rejected) {
            assertEquals(
                "accepted the spelling \"$text\"",
                InboxKeyReason.MALFORMED_KEY_MATERIAL,
                assertFailsWith<InboxKeyException> { InboxKeyMaterial.decode(text, 32) }.reason,
            )
        }
    }

    @Test
    fun `only the exact wrapped and content-key lengths are accepted`() {
        for (size in listOf(0, 47, 79, 81, 512)) {
            assertEquals(
                InboxKeyReason.MALFORMED_KEY_MATERIAL,
                assertFailsWith<InboxKeyException> {
                    InboxKeyMaterial.unsealContentKey(
                        algorithm,
                        InboxKeyMaterial.encode(ByteArray(size)),
                        keyPair,
                    )
                }.reason,
            )
        }
        for (size in listOf(0, 31, 33)) {
            assertEquals(
                InboxKeyReason.MALFORMED_KEY_MATERIAL,
                assertFailsWith<InboxKeyException> {
                    InboxKeyMaterial.sealContentKey(
                        algorithm,
                        InboxKeyMaterial.encode(recipientPublic),
                        ByteArray(size),
                    )
                }.reason,
            )
        }
    }

    // ── the key pair itself ─────────────────────────────────────────────────

    @Test
    fun `a key pair validates its halves, copies them, and refuses use after destroy`() {
        for (bad in listOf(0, 31, 33)) {
            assertEquals(
                InboxKeyReason.MALFORMED_KEY_MATERIAL,
                assertFailsWith<InboxKeyException> {
                    InboxDeviceKeyPair(ByteArray(bad), recipientPrivate)
                }.reason,
            )
            assertEquals(
                InboxKeyReason.MALFORMED_KEY_MATERIAL,
                assertFailsWith<InboxKeyException> {
                    InboxDeviceKeyPair(recipientPublic, ByteArray(bad))
                }.reason,
            )
        }

        val source = recipientPrivate.copyOf()
        val pair = InboxDeviceKeyPair(recipientPublic, source)
        Bytes.wipe(source)
        assertArrayEquals(recipientPrivate, pair.privateKeyCopy())
        // Mutating what was read back must not reach the stored key either.
        pair.privateKeyCopy().also { Bytes.wipe(it) }
        assertArrayEquals(recipientPrivate, pair.privateKeyCopy())

        pair.destroy()
        for (use in listOf<() -> Any>({ pair.publicKey }, { pair.privateKeyCopy() })) {
            assertEquals(InboxKeyReason.DESTROYED, assertFailsWith<InboxKeyException> { use() }.reason)
        }
        assertEquals(
            InboxKeyReason.DESTROYED,
            assertFailsWith<InboxKeyException> {
                InboxKeyMaterial.unsealContentKey(algorithm, InboxKeyMaterial.encode(sodiumSeal), pair)
            }.reason,
        )
    }

    @Test
    fun `nothing prints key material`() {
        val pair = InboxKeyMaterial.generateKeyPair()
        assertEquals("InboxDeviceKeyPair(redacted)", pair.toString())
        // A refusal names its reason and nothing about the input that caused it.
        val message = assertFailsWith<InboxKeyException> {
            InboxKeyMaterial.decode(InboxKeyMaterial.encode(recipientPublic) + "==", 32)
        }.message!!
        assertFalse(message.contains(InboxKeyMaterial.encode(recipientPublic)))
        assertEquals("relayium inbox key: MALFORMED_KEY_MATERIAL", message)
    }

    // ── known-answer tests for the composed primitives ──────────────────────

    @Test
    fun `Poly1305 takes the raw key as r then s -- RFC 8439 section 2_5_2`() {
        // The published vector, which fixes the ONE thing the sealed-box layout
        // cannot: whether the two 16-byte halves of the one-time key are swapped.
        val key = Bytes.unhex("85d6be7857556d337f4452fe42d506a80103808afb0db2fd4abff6af4149f51b")
        val message = "Cryptographic Forum Research Group".toByteArray(Charsets.US_ASCII)
        assertArrayEquals(
            Bytes.unhex("a8061dc1305136c6c22b8baf0c0127a9"),
            InboxKeyMaterial.poly1305(key, message),
        )
    }

    @Test
    fun `X25519 agrees with RFC 7748 section 6_1`() {
        val alicePrivate = Bytes.unhex("77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")
        val alicePublic = Bytes.unhex("8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a")
        val bobPrivate = Bytes.unhex("5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb")
        val bobPublic = Bytes.unhex("de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f")
        val shared = Bytes.unhex("4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742")

        // The raw agreement, pinned against the published answer: `beforeNm`
        // hashes it away, so this is the only place the curve step itself is
        // visible, and it is the step every wrapped key rests on.
        val agreed = ByteArray(32)
        assertTrue(X25519.calculateAgreement(alicePrivate, 0, bobPublic, 0, agreed, 0))
        assertArrayEquals(shared, agreed)
        assertArrayEquals(
            InboxKeyMaterial.beforeNm(alicePrivate, bobPublic),
            InboxKeyMaterial.beforeNm(bobPrivate, alicePublic),
        )
        assertArrayEquals(alicePublic, InboxDeviceKeyPair(alicePublic, alicePrivate).publicKey)
    }
}
